// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counters.proto

package dialog;

public final class Counters {
  private Counters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UnreadDialogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.UnreadDialog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasPeer();
    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Peers.Peer getPeer();
    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Peers.PeerOrBuilder getPeerOrBuilder();

    /**
     * <code>int32 counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    int getCounter();
  }
  /**
   * <pre>
   * Unread dialogs
   * peer dialog peer
   * counter unread messages count
   * </pre>
   *
   * Protobuf type {@code dialog.UnreadDialog}
   */
  public  static final class UnreadDialog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.UnreadDialog)
      UnreadDialogOrBuilder {
    // Use UnreadDialog.newBuilder() to construct.
    private UnreadDialog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnreadDialog() {
      counter_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UnreadDialog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              dialog.Peers.Peer.Builder subBuilder = null;
              if (peer_ != null) {
                subBuilder = peer_.toBuilder();
              }
              peer_ = input.readMessage(dialog.Peers.Peer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(peer_);
                peer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              counter_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.Counters.internal_static_dialog_UnreadDialog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.Counters.internal_static_dialog_UnreadDialog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.Counters.UnreadDialog.class, dialog.Counters.UnreadDialog.Builder.class);
    }

    public static final int PEER_FIELD_NUMBER = 1;
    private dialog.Peers.Peer peer_;
    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasPeer() {
      return peer_ != null;
    }
    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Peers.Peer getPeer() {
      return peer_ == null ? dialog.Peers.Peer.getDefaultInstance() : peer_;
    }
    /**
     * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Peers.PeerOrBuilder getPeerOrBuilder() {
      return getPeer();
    }

    public static final int COUNTER_FIELD_NUMBER = 2;
    private int counter_;
    /**
     * <code>int32 counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    public int getCounter() {
      return counter_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (peer_ != null) {
        output.writeMessage(1, getPeer());
      }
      if (counter_ != 0) {
        output.writeInt32(2, counter_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (peer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPeer());
      }
      if (counter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, counter_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.Counters.UnreadDialog)) {
        return super.equals(obj);
      }
      dialog.Counters.UnreadDialog other = (dialog.Counters.UnreadDialog) obj;

      boolean result = true;
      result = result && (hasPeer() == other.hasPeer());
      if (hasPeer()) {
        result = result && getPeer()
            .equals(other.getPeer());
      }
      result = result && (getCounter()
          == other.getCounter());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPeer()) {
        hash = (37 * hash) + PEER_FIELD_NUMBER;
        hash = (53 * hash) + getPeer().hashCode();
      }
      hash = (37 * hash) + COUNTER_FIELD_NUMBER;
      hash = (53 * hash) + getCounter();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.Counters.UnreadDialog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.UnreadDialog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.UnreadDialog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.UnreadDialog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.UnreadDialog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.UnreadDialog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.UnreadDialog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.Counters.UnreadDialog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.UnreadDialog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.UnreadDialog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.Counters.UnreadDialog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Unread dialogs
     * peer dialog peer
     * counter unread messages count
     * </pre>
     *
     * Protobuf type {@code dialog.UnreadDialog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.UnreadDialog)
        dialog.Counters.UnreadDialogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.Counters.internal_static_dialog_UnreadDialog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.Counters.internal_static_dialog_UnreadDialog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.Counters.UnreadDialog.class, dialog.Counters.UnreadDialog.Builder.class);
      }

      // Construct using dialog.Counters.UnreadDialog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (peerBuilder_ == null) {
          peer_ = null;
        } else {
          peer_ = null;
          peerBuilder_ = null;
        }
        counter_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.Counters.internal_static_dialog_UnreadDialog_descriptor;
      }

      public dialog.Counters.UnreadDialog getDefaultInstanceForType() {
        return dialog.Counters.UnreadDialog.getDefaultInstance();
      }

      public dialog.Counters.UnreadDialog build() {
        dialog.Counters.UnreadDialog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.Counters.UnreadDialog buildPartial() {
        dialog.Counters.UnreadDialog result = new dialog.Counters.UnreadDialog(this);
        if (peerBuilder_ == null) {
          result.peer_ = peer_;
        } else {
          result.peer_ = peerBuilder_.build();
        }
        result.counter_ = counter_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.Counters.UnreadDialog) {
          return mergeFrom((dialog.Counters.UnreadDialog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.Counters.UnreadDialog other) {
        if (other == dialog.Counters.UnreadDialog.getDefaultInstance()) return this;
        if (other.hasPeer()) {
          mergePeer(other.getPeer());
        }
        if (other.getCounter() != 0) {
          setCounter(other.getCounter());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.Counters.UnreadDialog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.Counters.UnreadDialog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private dialog.Peers.Peer peer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          dialog.Peers.Peer, dialog.Peers.Peer.Builder, dialog.Peers.PeerOrBuilder> peerBuilder_;
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasPeer() {
        return peerBuilder_ != null || peer_ != null;
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Peers.Peer getPeer() {
        if (peerBuilder_ == null) {
          return peer_ == null ? dialog.Peers.Peer.getDefaultInstance() : peer_;
        } else {
          return peerBuilder_.getMessage();
        }
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPeer(dialog.Peers.Peer value) {
        if (peerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          peer_ = value;
          onChanged();
        } else {
          peerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPeer(
          dialog.Peers.Peer.Builder builderForValue) {
        if (peerBuilder_ == null) {
          peer_ = builderForValue.build();
          onChanged();
        } else {
          peerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergePeer(dialog.Peers.Peer value) {
        if (peerBuilder_ == null) {
          if (peer_ != null) {
            peer_ =
              dialog.Peers.Peer.newBuilder(peer_).mergeFrom(value).buildPartial();
          } else {
            peer_ = value;
          }
          onChanged();
        } else {
          peerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearPeer() {
        if (peerBuilder_ == null) {
          peer_ = null;
          onChanged();
        } else {
          peer_ = null;
          peerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Peers.Peer.Builder getPeerBuilder() {
        
        onChanged();
        return getPeerFieldBuilder().getBuilder();
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Peers.PeerOrBuilder getPeerOrBuilder() {
        if (peerBuilder_ != null) {
          return peerBuilder_.getMessageOrBuilder();
        } else {
          return peer_ == null ?
              dialog.Peers.Peer.getDefaultInstance() : peer_;
        }
      }
      /**
       * <code>.dialog.Peer peer = 1 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dialog.Peers.Peer, dialog.Peers.Peer.Builder, dialog.Peers.PeerOrBuilder> 
          getPeerFieldBuilder() {
        if (peerBuilder_ == null) {
          peerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dialog.Peers.Peer, dialog.Peers.Peer.Builder, dialog.Peers.PeerOrBuilder>(
                  getPeer(),
                  getParentForChildren(),
                  isClean());
          peer_ = null;
        }
        return peerBuilder_;
      }

      private int counter_ ;
      /**
       * <code>int32 counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public int getCounter() {
        return counter_;
      }
      /**
       * <code>int32 counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setCounter(int value) {
        
        counter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearCounter() {
        
        counter_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.UnreadDialog)
    }

    // @@protoc_insertion_point(class_scope:dialog.UnreadDialog)
    private static final dialog.Counters.UnreadDialog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.Counters.UnreadDialog();
    }

    public static dialog.Counters.UnreadDialog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnreadDialog>
        PARSER = new com.google.protobuf.AbstractParser<UnreadDialog>() {
      public UnreadDialog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UnreadDialog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnreadDialog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnreadDialog> getParserForType() {
      return PARSER;
    }

    public dialog.Counters.UnreadDialog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppCountersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.AppCounters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasGlobalCounter();
    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int32Value getGlobalCounter();
    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getGlobalCounterOrBuilder();

    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasGlobalDialogsCounter();
    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int32Value getGlobalDialogsCounter();
    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getGlobalDialogsCounterOrBuilder();

    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    java.util.List<dialog.Counters.UnreadDialog> 
        getUnreadDialogsList();
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Counters.UnreadDialog getUnreadDialogs(int index);
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    int getUnreadDialogsCount();
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    java.util.List<? extends dialog.Counters.UnreadDialogOrBuilder> 
        getUnreadDialogsOrBuilderList();
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Counters.UnreadDialogOrBuilder getUnreadDialogsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Application counters
   * globalCounter Global unread counter
   * globalDialogsCounter Global count of dialogs with positive counter values
   * unreadDialogs map of chat peer id to unread to counters
   * </pre>
   *
   * Protobuf type {@code dialog.AppCounters}
   */
  public  static final class AppCounters extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.AppCounters)
      AppCountersOrBuilder {
    // Use AppCounters.newBuilder() to construct.
    private AppCounters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppCounters() {
      unreadDialogs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppCounters(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (globalCounter_ != null) {
                subBuilder = globalCounter_.toBuilder();
              }
              globalCounter_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(globalCounter_);
                globalCounter_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (globalDialogsCounter_ != null) {
                subBuilder = globalDialogsCounter_.toBuilder();
              }
              globalDialogsCounter_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(globalDialogsCounter_);
                globalDialogsCounter_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                unreadDialogs_ = new java.util.ArrayList<dialog.Counters.UnreadDialog>();
                mutable_bitField0_ |= 0x00000004;
              }
              unreadDialogs_.add(
                  input.readMessage(dialog.Counters.UnreadDialog.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          unreadDialogs_ = java.util.Collections.unmodifiableList(unreadDialogs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.Counters.internal_static_dialog_AppCounters_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.Counters.internal_static_dialog_AppCounters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.Counters.AppCounters.class, dialog.Counters.AppCounters.Builder.class);
    }

    private int bitField0_;
    public static final int GLOBAL_COUNTER_FIELD_NUMBER = 1;
    private com.google.protobuf.Int32Value globalCounter_;
    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasGlobalCounter() {
      return globalCounter_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int32Value getGlobalCounter() {
      return globalCounter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : globalCounter_;
    }
    /**
     * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getGlobalCounterOrBuilder() {
      return getGlobalCounter();
    }

    public static final int GLOBAL_DIALOGS_COUNTER_FIELD_NUMBER = 2;
    private com.google.protobuf.Int32Value globalDialogsCounter_;
    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasGlobalDialogsCounter() {
      return globalDialogsCounter_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int32Value getGlobalDialogsCounter() {
      return globalDialogsCounter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : globalDialogsCounter_;
    }
    /**
     * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getGlobalDialogsCounterOrBuilder() {
      return getGlobalDialogsCounter();
    }

    public static final int UNREAD_DIALOGS_FIELD_NUMBER = 3;
    private java.util.List<dialog.Counters.UnreadDialog> unreadDialogs_;
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    public java.util.List<dialog.Counters.UnreadDialog> getUnreadDialogsList() {
      return unreadDialogs_;
    }
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    public java.util.List<? extends dialog.Counters.UnreadDialogOrBuilder> 
        getUnreadDialogsOrBuilderList() {
      return unreadDialogs_;
    }
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    public int getUnreadDialogsCount() {
      return unreadDialogs_.size();
    }
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Counters.UnreadDialog getUnreadDialogs(int index) {
      return unreadDialogs_.get(index);
    }
    /**
     * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Counters.UnreadDialogOrBuilder getUnreadDialogsOrBuilder(
        int index) {
      return unreadDialogs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (globalCounter_ != null) {
        output.writeMessage(1, getGlobalCounter());
      }
      if (globalDialogsCounter_ != null) {
        output.writeMessage(2, getGlobalDialogsCounter());
      }
      for (int i = 0; i < unreadDialogs_.size(); i++) {
        output.writeMessage(3, unreadDialogs_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (globalCounter_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGlobalCounter());
      }
      if (globalDialogsCounter_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGlobalDialogsCounter());
      }
      for (int i = 0; i < unreadDialogs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, unreadDialogs_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.Counters.AppCounters)) {
        return super.equals(obj);
      }
      dialog.Counters.AppCounters other = (dialog.Counters.AppCounters) obj;

      boolean result = true;
      result = result && (hasGlobalCounter() == other.hasGlobalCounter());
      if (hasGlobalCounter()) {
        result = result && getGlobalCounter()
            .equals(other.getGlobalCounter());
      }
      result = result && (hasGlobalDialogsCounter() == other.hasGlobalDialogsCounter());
      if (hasGlobalDialogsCounter()) {
        result = result && getGlobalDialogsCounter()
            .equals(other.getGlobalDialogsCounter());
      }
      result = result && getUnreadDialogsList()
          .equals(other.getUnreadDialogsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGlobalCounter()) {
        hash = (37 * hash) + GLOBAL_COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + getGlobalCounter().hashCode();
      }
      if (hasGlobalDialogsCounter()) {
        hash = (37 * hash) + GLOBAL_DIALOGS_COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + getGlobalDialogsCounter().hashCode();
      }
      if (getUnreadDialogsCount() > 0) {
        hash = (37 * hash) + UNREAD_DIALOGS_FIELD_NUMBER;
        hash = (53 * hash) + getUnreadDialogsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.Counters.AppCounters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.AppCounters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.AppCounters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.AppCounters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.AppCounters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.AppCounters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.AppCounters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.Counters.AppCounters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.AppCounters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.AppCounters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.Counters.AppCounters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Application counters
     * globalCounter Global unread counter
     * globalDialogsCounter Global count of dialogs with positive counter values
     * unreadDialogs map of chat peer id to unread to counters
     * </pre>
     *
     * Protobuf type {@code dialog.AppCounters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.AppCounters)
        dialog.Counters.AppCountersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.Counters.internal_static_dialog_AppCounters_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.Counters.internal_static_dialog_AppCounters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.Counters.AppCounters.class, dialog.Counters.AppCounters.Builder.class);
      }

      // Construct using dialog.Counters.AppCounters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUnreadDialogsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (globalCounterBuilder_ == null) {
          globalCounter_ = null;
        } else {
          globalCounter_ = null;
          globalCounterBuilder_ = null;
        }
        if (globalDialogsCounterBuilder_ == null) {
          globalDialogsCounter_ = null;
        } else {
          globalDialogsCounter_ = null;
          globalDialogsCounterBuilder_ = null;
        }
        if (unreadDialogsBuilder_ == null) {
          unreadDialogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          unreadDialogsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.Counters.internal_static_dialog_AppCounters_descriptor;
      }

      public dialog.Counters.AppCounters getDefaultInstanceForType() {
        return dialog.Counters.AppCounters.getDefaultInstance();
      }

      public dialog.Counters.AppCounters build() {
        dialog.Counters.AppCounters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.Counters.AppCounters buildPartial() {
        dialog.Counters.AppCounters result = new dialog.Counters.AppCounters(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (globalCounterBuilder_ == null) {
          result.globalCounter_ = globalCounter_;
        } else {
          result.globalCounter_ = globalCounterBuilder_.build();
        }
        if (globalDialogsCounterBuilder_ == null) {
          result.globalDialogsCounter_ = globalDialogsCounter_;
        } else {
          result.globalDialogsCounter_ = globalDialogsCounterBuilder_.build();
        }
        if (unreadDialogsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            unreadDialogs_ = java.util.Collections.unmodifiableList(unreadDialogs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.unreadDialogs_ = unreadDialogs_;
        } else {
          result.unreadDialogs_ = unreadDialogsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.Counters.AppCounters) {
          return mergeFrom((dialog.Counters.AppCounters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.Counters.AppCounters other) {
        if (other == dialog.Counters.AppCounters.getDefaultInstance()) return this;
        if (other.hasGlobalCounter()) {
          mergeGlobalCounter(other.getGlobalCounter());
        }
        if (other.hasGlobalDialogsCounter()) {
          mergeGlobalDialogsCounter(other.getGlobalDialogsCounter());
        }
        if (unreadDialogsBuilder_ == null) {
          if (!other.unreadDialogs_.isEmpty()) {
            if (unreadDialogs_.isEmpty()) {
              unreadDialogs_ = other.unreadDialogs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureUnreadDialogsIsMutable();
              unreadDialogs_.addAll(other.unreadDialogs_);
            }
            onChanged();
          }
        } else {
          if (!other.unreadDialogs_.isEmpty()) {
            if (unreadDialogsBuilder_.isEmpty()) {
              unreadDialogsBuilder_.dispose();
              unreadDialogsBuilder_ = null;
              unreadDialogs_ = other.unreadDialogs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              unreadDialogsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUnreadDialogsFieldBuilder() : null;
            } else {
              unreadDialogsBuilder_.addAllMessages(other.unreadDialogs_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.Counters.AppCounters parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.Counters.AppCounters) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Int32Value globalCounter_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> globalCounterBuilder_;
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasGlobalCounter() {
        return globalCounterBuilder_ != null || globalCounter_ != null;
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32Value getGlobalCounter() {
        if (globalCounterBuilder_ == null) {
          return globalCounter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : globalCounter_;
        } else {
          return globalCounterBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setGlobalCounter(com.google.protobuf.Int32Value value) {
        if (globalCounterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          globalCounter_ = value;
          onChanged();
        } else {
          globalCounterBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setGlobalCounter(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (globalCounterBuilder_ == null) {
          globalCounter_ = builderForValue.build();
          onChanged();
        } else {
          globalCounterBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeGlobalCounter(com.google.protobuf.Int32Value value) {
        if (globalCounterBuilder_ == null) {
          if (globalCounter_ != null) {
            globalCounter_ =
              com.google.protobuf.Int32Value.newBuilder(globalCounter_).mergeFrom(value).buildPartial();
          } else {
            globalCounter_ = value;
          }
          onChanged();
        } else {
          globalCounterBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearGlobalCounter() {
        if (globalCounterBuilder_ == null) {
          globalCounter_ = null;
          onChanged();
        } else {
          globalCounter_ = null;
          globalCounterBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32Value.Builder getGlobalCounterBuilder() {
        
        onChanged();
        return getGlobalCounterFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getGlobalCounterOrBuilder() {
        if (globalCounterBuilder_ != null) {
          return globalCounterBuilder_.getMessageOrBuilder();
        } else {
          return globalCounter_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : globalCounter_;
        }
      }
      /**
       * <code>.google.protobuf.Int32Value global_counter = 1 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getGlobalCounterFieldBuilder() {
        if (globalCounterBuilder_ == null) {
          globalCounterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getGlobalCounter(),
                  getParentForChildren(),
                  isClean());
          globalCounter_ = null;
        }
        return globalCounterBuilder_;
      }

      private com.google.protobuf.Int32Value globalDialogsCounter_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> globalDialogsCounterBuilder_;
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasGlobalDialogsCounter() {
        return globalDialogsCounterBuilder_ != null || globalDialogsCounter_ != null;
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32Value getGlobalDialogsCounter() {
        if (globalDialogsCounterBuilder_ == null) {
          return globalDialogsCounter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : globalDialogsCounter_;
        } else {
          return globalDialogsCounterBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setGlobalDialogsCounter(com.google.protobuf.Int32Value value) {
        if (globalDialogsCounterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          globalDialogsCounter_ = value;
          onChanged();
        } else {
          globalDialogsCounterBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setGlobalDialogsCounter(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (globalDialogsCounterBuilder_ == null) {
          globalDialogsCounter_ = builderForValue.build();
          onChanged();
        } else {
          globalDialogsCounterBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeGlobalDialogsCounter(com.google.protobuf.Int32Value value) {
        if (globalDialogsCounterBuilder_ == null) {
          if (globalDialogsCounter_ != null) {
            globalDialogsCounter_ =
              com.google.protobuf.Int32Value.newBuilder(globalDialogsCounter_).mergeFrom(value).buildPartial();
          } else {
            globalDialogsCounter_ = value;
          }
          onChanged();
        } else {
          globalDialogsCounterBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearGlobalDialogsCounter() {
        if (globalDialogsCounterBuilder_ == null) {
          globalDialogsCounter_ = null;
          onChanged();
        } else {
          globalDialogsCounter_ = null;
          globalDialogsCounterBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32Value.Builder getGlobalDialogsCounterBuilder() {
        
        onChanged();
        return getGlobalDialogsCounterFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getGlobalDialogsCounterOrBuilder() {
        if (globalDialogsCounterBuilder_ != null) {
          return globalDialogsCounterBuilder_.getMessageOrBuilder();
        } else {
          return globalDialogsCounter_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : globalDialogsCounter_;
        }
      }
      /**
       * <code>.google.protobuf.Int32Value global_dialogs_counter = 2 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getGlobalDialogsCounterFieldBuilder() {
        if (globalDialogsCounterBuilder_ == null) {
          globalDialogsCounterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getGlobalDialogsCounter(),
                  getParentForChildren(),
                  isClean());
          globalDialogsCounter_ = null;
        }
        return globalDialogsCounterBuilder_;
      }

      private java.util.List<dialog.Counters.UnreadDialog> unreadDialogs_ =
        java.util.Collections.emptyList();
      private void ensureUnreadDialogsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          unreadDialogs_ = new java.util.ArrayList<dialog.Counters.UnreadDialog>(unreadDialogs_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          dialog.Counters.UnreadDialog, dialog.Counters.UnreadDialog.Builder, dialog.Counters.UnreadDialogOrBuilder> unreadDialogsBuilder_;

      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public java.util.List<dialog.Counters.UnreadDialog> getUnreadDialogsList() {
        if (unreadDialogsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(unreadDialogs_);
        } else {
          return unreadDialogsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public int getUnreadDialogsCount() {
        if (unreadDialogsBuilder_ == null) {
          return unreadDialogs_.size();
        } else {
          return unreadDialogsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.UnreadDialog getUnreadDialogs(int index) {
        if (unreadDialogsBuilder_ == null) {
          return unreadDialogs_.get(index);
        } else {
          return unreadDialogsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setUnreadDialogs(
          int index, dialog.Counters.UnreadDialog value) {
        if (unreadDialogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.set(index, value);
          onChanged();
        } else {
          unreadDialogsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setUnreadDialogs(
          int index, dialog.Counters.UnreadDialog.Builder builderForValue) {
        if (unreadDialogsBuilder_ == null) {
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.set(index, builderForValue.build());
          onChanged();
        } else {
          unreadDialogsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addUnreadDialogs(dialog.Counters.UnreadDialog value) {
        if (unreadDialogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.add(value);
          onChanged();
        } else {
          unreadDialogsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addUnreadDialogs(
          int index, dialog.Counters.UnreadDialog value) {
        if (unreadDialogsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.add(index, value);
          onChanged();
        } else {
          unreadDialogsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addUnreadDialogs(
          dialog.Counters.UnreadDialog.Builder builderForValue) {
        if (unreadDialogsBuilder_ == null) {
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.add(builderForValue.build());
          onChanged();
        } else {
          unreadDialogsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addUnreadDialogs(
          int index, dialog.Counters.UnreadDialog.Builder builderForValue) {
        if (unreadDialogsBuilder_ == null) {
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.add(index, builderForValue.build());
          onChanged();
        } else {
          unreadDialogsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addAllUnreadDialogs(
          java.lang.Iterable<? extends dialog.Counters.UnreadDialog> values) {
        if (unreadDialogsBuilder_ == null) {
          ensureUnreadDialogsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, unreadDialogs_);
          onChanged();
        } else {
          unreadDialogsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearUnreadDialogs() {
        if (unreadDialogsBuilder_ == null) {
          unreadDialogs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          unreadDialogsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder removeUnreadDialogs(int index) {
        if (unreadDialogsBuilder_ == null) {
          ensureUnreadDialogsIsMutable();
          unreadDialogs_.remove(index);
          onChanged();
        } else {
          unreadDialogsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.UnreadDialog.Builder getUnreadDialogsBuilder(
          int index) {
        return getUnreadDialogsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.UnreadDialogOrBuilder getUnreadDialogsOrBuilder(
          int index) {
        if (unreadDialogsBuilder_ == null) {
          return unreadDialogs_.get(index);  } else {
          return unreadDialogsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public java.util.List<? extends dialog.Counters.UnreadDialogOrBuilder> 
           getUnreadDialogsOrBuilderList() {
        if (unreadDialogsBuilder_ != null) {
          return unreadDialogsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(unreadDialogs_);
        }
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.UnreadDialog.Builder addUnreadDialogsBuilder() {
        return getUnreadDialogsFieldBuilder().addBuilder(
            dialog.Counters.UnreadDialog.getDefaultInstance());
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.UnreadDialog.Builder addUnreadDialogsBuilder(
          int index) {
        return getUnreadDialogsFieldBuilder().addBuilder(
            index, dialog.Counters.UnreadDialog.getDefaultInstance());
      }
      /**
       * <code>repeated .dialog.UnreadDialog unread_dialogs = 3 [(.dialog.dlg) = { ... }</code>
       */
      public java.util.List<dialog.Counters.UnreadDialog.Builder> 
           getUnreadDialogsBuilderList() {
        return getUnreadDialogsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          dialog.Counters.UnreadDialog, dialog.Counters.UnreadDialog.Builder, dialog.Counters.UnreadDialogOrBuilder> 
          getUnreadDialogsFieldBuilder() {
        if (unreadDialogsBuilder_ == null) {
          unreadDialogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              dialog.Counters.UnreadDialog, dialog.Counters.UnreadDialog.Builder, dialog.Counters.UnreadDialogOrBuilder>(
                  unreadDialogs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          unreadDialogs_ = null;
        }
        return unreadDialogsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.AppCounters)
    }

    // @@protoc_insertion_point(class_scope:dialog.AppCounters)
    private static final dialog.Counters.AppCounters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.Counters.AppCounters();
    }

    public static dialog.Counters.AppCounters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppCounters>
        PARSER = new com.google.protobuf.AbstractParser<AppCounters>() {
      public AppCounters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppCounters(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppCounters> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppCounters> getParserForType() {
      return PARSER;
    }

    public dialog.Counters.AppCounters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateCountersChangedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.UpdateCountersChanged)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasCounters();
    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Counters.AppCounters getCounters();
    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    dialog.Counters.AppCountersOrBuilder getCountersOrBuilder();

    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasTs();
    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int64Value getTs();
    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getTsOrBuilder();
  }
  /**
   * <pre>
   * Update about counters changed
   * </pre>
   *
   * Protobuf type {@code dialog.UpdateCountersChanged}
   */
  public  static final class UpdateCountersChanged extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.UpdateCountersChanged)
      UpdateCountersChangedOrBuilder {
    // Use UpdateCountersChanged.newBuilder() to construct.
    private UpdateCountersChanged(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateCountersChanged() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateCountersChanged(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              dialog.Counters.AppCounters.Builder subBuilder = null;
              if (counters_ != null) {
                subBuilder = counters_.toBuilder();
              }
              counters_ = input.readMessage(dialog.Counters.AppCounters.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(counters_);
                counters_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (ts_ != null) {
                subBuilder = ts_.toBuilder();
              }
              ts_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ts_);
                ts_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.Counters.internal_static_dialog_UpdateCountersChanged_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.Counters.internal_static_dialog_UpdateCountersChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.Counters.UpdateCountersChanged.class, dialog.Counters.UpdateCountersChanged.Builder.class);
    }

    public static final int COUNTERS_FIELD_NUMBER = 1;
    private dialog.Counters.AppCounters counters_;
    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasCounters() {
      return counters_ != null;
    }
    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Counters.AppCounters getCounters() {
      return counters_ == null ? dialog.Counters.AppCounters.getDefaultInstance() : counters_;
    }
    /**
     * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.Counters.AppCountersOrBuilder getCountersOrBuilder() {
      return getCounters();
    }

    public static final int TS_FIELD_NUMBER = 2;
    private com.google.protobuf.Int64Value ts_;
    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasTs() {
      return ts_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int64Value getTs() {
      return ts_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : ts_;
    }
    /**
     * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getTsOrBuilder() {
      return getTs();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (counters_ != null) {
        output.writeMessage(1, getCounters());
      }
      if (ts_ != null) {
        output.writeMessage(2, getTs());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (counters_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCounters());
      }
      if (ts_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTs());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.Counters.UpdateCountersChanged)) {
        return super.equals(obj);
      }
      dialog.Counters.UpdateCountersChanged other = (dialog.Counters.UpdateCountersChanged) obj;

      boolean result = true;
      result = result && (hasCounters() == other.hasCounters());
      if (hasCounters()) {
        result = result && getCounters()
            .equals(other.getCounters());
      }
      result = result && (hasTs() == other.hasTs());
      if (hasTs()) {
        result = result && getTs()
            .equals(other.getTs());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCounters()) {
        hash = (37 * hash) + COUNTERS_FIELD_NUMBER;
        hash = (53 * hash) + getCounters().hashCode();
      }
      if (hasTs()) {
        hash = (37 * hash) + TS_FIELD_NUMBER;
        hash = (53 * hash) + getTs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.Counters.UpdateCountersChanged parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.UpdateCountersChanged parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.Counters.UpdateCountersChanged parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.Counters.UpdateCountersChanged parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.Counters.UpdateCountersChanged prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Update about counters changed
     * </pre>
     *
     * Protobuf type {@code dialog.UpdateCountersChanged}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.UpdateCountersChanged)
        dialog.Counters.UpdateCountersChangedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.Counters.internal_static_dialog_UpdateCountersChanged_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.Counters.internal_static_dialog_UpdateCountersChanged_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.Counters.UpdateCountersChanged.class, dialog.Counters.UpdateCountersChanged.Builder.class);
      }

      // Construct using dialog.Counters.UpdateCountersChanged.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (countersBuilder_ == null) {
          counters_ = null;
        } else {
          counters_ = null;
          countersBuilder_ = null;
        }
        if (tsBuilder_ == null) {
          ts_ = null;
        } else {
          ts_ = null;
          tsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.Counters.internal_static_dialog_UpdateCountersChanged_descriptor;
      }

      public dialog.Counters.UpdateCountersChanged getDefaultInstanceForType() {
        return dialog.Counters.UpdateCountersChanged.getDefaultInstance();
      }

      public dialog.Counters.UpdateCountersChanged build() {
        dialog.Counters.UpdateCountersChanged result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.Counters.UpdateCountersChanged buildPartial() {
        dialog.Counters.UpdateCountersChanged result = new dialog.Counters.UpdateCountersChanged(this);
        if (countersBuilder_ == null) {
          result.counters_ = counters_;
        } else {
          result.counters_ = countersBuilder_.build();
        }
        if (tsBuilder_ == null) {
          result.ts_ = ts_;
        } else {
          result.ts_ = tsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.Counters.UpdateCountersChanged) {
          return mergeFrom((dialog.Counters.UpdateCountersChanged)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.Counters.UpdateCountersChanged other) {
        if (other == dialog.Counters.UpdateCountersChanged.getDefaultInstance()) return this;
        if (other.hasCounters()) {
          mergeCounters(other.getCounters());
        }
        if (other.hasTs()) {
          mergeTs(other.getTs());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.Counters.UpdateCountersChanged parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.Counters.UpdateCountersChanged) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private dialog.Counters.AppCounters counters_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          dialog.Counters.AppCounters, dialog.Counters.AppCounters.Builder, dialog.Counters.AppCountersOrBuilder> countersBuilder_;
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasCounters() {
        return countersBuilder_ != null || counters_ != null;
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.AppCounters getCounters() {
        if (countersBuilder_ == null) {
          return counters_ == null ? dialog.Counters.AppCounters.getDefaultInstance() : counters_;
        } else {
          return countersBuilder_.getMessage();
        }
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setCounters(dialog.Counters.AppCounters value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          counters_ = value;
          onChanged();
        } else {
          countersBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setCounters(
          dialog.Counters.AppCounters.Builder builderForValue) {
        if (countersBuilder_ == null) {
          counters_ = builderForValue.build();
          onChanged();
        } else {
          countersBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeCounters(dialog.Counters.AppCounters value) {
        if (countersBuilder_ == null) {
          if (counters_ != null) {
            counters_ =
              dialog.Counters.AppCounters.newBuilder(counters_).mergeFrom(value).buildPartial();
          } else {
            counters_ = value;
          }
          onChanged();
        } else {
          countersBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearCounters() {
        if (countersBuilder_ == null) {
          counters_ = null;
          onChanged();
        } else {
          counters_ = null;
          countersBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.AppCounters.Builder getCountersBuilder() {
        
        onChanged();
        return getCountersFieldBuilder().getBuilder();
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.Counters.AppCountersOrBuilder getCountersOrBuilder() {
        if (countersBuilder_ != null) {
          return countersBuilder_.getMessageOrBuilder();
        } else {
          return counters_ == null ?
              dialog.Counters.AppCounters.getDefaultInstance() : counters_;
        }
      }
      /**
       * <code>.dialog.AppCounters counters = 1 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          dialog.Counters.AppCounters, dialog.Counters.AppCounters.Builder, dialog.Counters.AppCountersOrBuilder> 
          getCountersFieldBuilder() {
        if (countersBuilder_ == null) {
          countersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              dialog.Counters.AppCounters, dialog.Counters.AppCounters.Builder, dialog.Counters.AppCountersOrBuilder>(
                  getCounters(),
                  getParentForChildren(),
                  isClean());
          counters_ = null;
        }
        return countersBuilder_;
      }

      private com.google.protobuf.Int64Value ts_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> tsBuilder_;
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasTs() {
        return tsBuilder_ != null || ts_ != null;
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int64Value getTs() {
        if (tsBuilder_ == null) {
          return ts_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : ts_;
        } else {
          return tsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTs(com.google.protobuf.Int64Value value) {
        if (tsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ts_ = value;
          onChanged();
        } else {
          tsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTs(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (tsBuilder_ == null) {
          ts_ = builderForValue.build();
          onChanged();
        } else {
          tsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeTs(com.google.protobuf.Int64Value value) {
        if (tsBuilder_ == null) {
          if (ts_ != null) {
            ts_ =
              com.google.protobuf.Int64Value.newBuilder(ts_).mergeFrom(value).buildPartial();
          } else {
            ts_ = value;
          }
          onChanged();
        } else {
          tsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearTs() {
        if (tsBuilder_ == null) {
          ts_ = null;
          onChanged();
        } else {
          ts_ = null;
          tsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int64Value.Builder getTsBuilder() {
        
        onChanged();
        return getTsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getTsOrBuilder() {
        if (tsBuilder_ != null) {
          return tsBuilder_.getMessageOrBuilder();
        } else {
          return ts_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : ts_;
        }
      }
      /**
       * <code>.google.protobuf.Int64Value ts = 2 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getTsFieldBuilder() {
        if (tsBuilder_ == null) {
          tsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getTs(),
                  getParentForChildren(),
                  isClean());
          ts_ = null;
        }
        return tsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.UpdateCountersChanged)
    }

    // @@protoc_insertion_point(class_scope:dialog.UpdateCountersChanged)
    private static final dialog.Counters.UpdateCountersChanged DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.Counters.UpdateCountersChanged();
    }

    public static dialog.Counters.UpdateCountersChanged getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateCountersChanged>
        PARSER = new com.google.protobuf.AbstractParser<UpdateCountersChanged>() {
      public UpdateCountersChanged parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateCountersChanged(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateCountersChanged> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateCountersChanged> getParserForType() {
      return PARSER;
    }

    public dialog.Counters.UpdateCountersChanged getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_UnreadDialog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_UnreadDialog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_AppCounters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_AppCounters_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_UpdateCountersChanged_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_UpdateCountersChanged_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016counters.proto\022\006dialog\032\036google/protobu" +
      "f/wrappers.proto\032\034google/api/annotations" +
      ".proto\032\021definitions.proto\032\013peers.proto\032\025" +
      "scalapb/scalapb.proto\"Y\n\014UnreadDialog\022)\n" +
      "\004peer\030\001 \001(\0132\014.dialog.PeerB\r\212\3520\t\n\007visible" +
      "\022\036\n\007counter\030\002 \001(\005B\r\212\3520\t\n\007visible\"\332\001\n\013App" +
      "Counters\022B\n\016global_counter\030\001 \001(\0132\033.googl" +
      "e.protobuf.Int32ValueB\r\212\3520\t\n\007visible\022J\n\026" +
      "global_dialogs_counter\030\002 \001(\0132\033.google.pr" +
      "otobuf.Int32ValueB\r\212\3520\t\n\007visible\022;\n\016unre",
      "ad_dialogs\030\003 \003(\0132\024.dialog.UnreadDialogB\r" +
      "\212\3520\t\n\007visible\"\205\001\n\025UpdateCountersChanged\022" +
      "4\n\010counters\030\001 \001(\0132\023.dialog.AppCountersB\r" +
      "\212\3520\t\n\007visible\0226\n\002ts\030\002 \001(\0132\033.google.proto" +
      "buf.Int64ValueB\r\212\3520\t\n\007visibleB\031\342?\026\n\024im.d" +
      "lg.grpc.servicesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          dialog.Definitions.getDescriptor(),
          dialog.Peers.getDescriptor(),
          com.trueaccord.scalapb.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_dialog_UnreadDialog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialog_UnreadDialog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_UnreadDialog_descriptor,
        new java.lang.String[] { "Peer", "Counter", });
    internal_static_dialog_AppCounters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialog_AppCounters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_AppCounters_descriptor,
        new java.lang.String[] { "GlobalCounter", "GlobalDialogsCounter", "UnreadDialogs", });
    internal_static_dialog_UpdateCountersChanged_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dialog_UpdateCountersChanged_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_UpdateCountersChanged_descriptor,
        new java.lang.String[] { "Counters", "Ts", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(dialog.Definitions.dlg);
    registry.add(com.trueaccord.scalapb.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    dialog.Definitions.getDescriptor();
    dialog.Peers.getDescriptor();
    com.trueaccord.scalapb.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
