// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto.proto

package dialog;

public final class CryptoOuterClass {
  private CryptoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestKeyExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RequestKeyExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasClientKey();
    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.BytesValue getClientKey();
    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.BytesValueOrBuilder getClientKeyOrBuilder();
  }
  /**
   * <pre>
   * Exchange public keys
   * </pre>
   *
   * Protobuf type {@code dialog.RequestKeyExchange}
   */
  public  static final class RequestKeyExchange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RequestKeyExchange)
      RequestKeyExchangeOrBuilder {
    // Use RequestKeyExchange.newBuilder() to construct.
    private RequestKeyExchange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestKeyExchange() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestKeyExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.BytesValue.Builder subBuilder = null;
              if (clientKey_ != null) {
                subBuilder = clientKey_.toBuilder();
              }
              clientKey_ = input.readMessage(com.google.protobuf.BytesValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clientKey_);
                clientKey_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.CryptoOuterClass.internal_static_dialog_RequestKeyExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.CryptoOuterClass.internal_static_dialog_RequestKeyExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.CryptoOuterClass.RequestKeyExchange.class, dialog.CryptoOuterClass.RequestKeyExchange.Builder.class);
    }

    public static final int CLIENT_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.BytesValue clientKey_;
    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasClientKey() {
      return clientKey_ != null;
    }
    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.BytesValue getClientKey() {
      return clientKey_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : clientKey_;
    }
    /**
     * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getClientKeyOrBuilder() {
      return getClientKey();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientKey_ != null) {
        output.writeMessage(1, getClientKey());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getClientKey());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.CryptoOuterClass.RequestKeyExchange)) {
        return super.equals(obj);
      }
      dialog.CryptoOuterClass.RequestKeyExchange other = (dialog.CryptoOuterClass.RequestKeyExchange) obj;

      boolean result = true;
      result = result && (hasClientKey() == other.hasClientKey());
      if (hasClientKey()) {
        result = result && getClientKey()
            .equals(other.getClientKey());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientKey()) {
        hash = (37 * hash) + CLIENT_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getClientKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.RequestKeyExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.CryptoOuterClass.RequestKeyExchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Exchange public keys
     * </pre>
     *
     * Protobuf type {@code dialog.RequestKeyExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RequestKeyExchange)
        dialog.CryptoOuterClass.RequestKeyExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.CryptoOuterClass.internal_static_dialog_RequestKeyExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.CryptoOuterClass.internal_static_dialog_RequestKeyExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.CryptoOuterClass.RequestKeyExchange.class, dialog.CryptoOuterClass.RequestKeyExchange.Builder.class);
      }

      // Construct using dialog.CryptoOuterClass.RequestKeyExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (clientKeyBuilder_ == null) {
          clientKey_ = null;
        } else {
          clientKey_ = null;
          clientKeyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.CryptoOuterClass.internal_static_dialog_RequestKeyExchange_descriptor;
      }

      public dialog.CryptoOuterClass.RequestKeyExchange getDefaultInstanceForType() {
        return dialog.CryptoOuterClass.RequestKeyExchange.getDefaultInstance();
      }

      public dialog.CryptoOuterClass.RequestKeyExchange build() {
        dialog.CryptoOuterClass.RequestKeyExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.CryptoOuterClass.RequestKeyExchange buildPartial() {
        dialog.CryptoOuterClass.RequestKeyExchange result = new dialog.CryptoOuterClass.RequestKeyExchange(this);
        if (clientKeyBuilder_ == null) {
          result.clientKey_ = clientKey_;
        } else {
          result.clientKey_ = clientKeyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.CryptoOuterClass.RequestKeyExchange) {
          return mergeFrom((dialog.CryptoOuterClass.RequestKeyExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.CryptoOuterClass.RequestKeyExchange other) {
        if (other == dialog.CryptoOuterClass.RequestKeyExchange.getDefaultInstance()) return this;
        if (other.hasClientKey()) {
          mergeClientKey(other.getClientKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.CryptoOuterClass.RequestKeyExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.CryptoOuterClass.RequestKeyExchange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.BytesValue clientKey_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> clientKeyBuilder_;
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasClientKey() {
        return clientKeyBuilder_ != null || clientKey_ != null;
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValue getClientKey() {
        if (clientKeyBuilder_ == null) {
          return clientKey_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : clientKey_;
        } else {
          return clientKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setClientKey(com.google.protobuf.BytesValue value) {
        if (clientKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientKey_ = value;
          onChanged();
        } else {
          clientKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setClientKey(
          com.google.protobuf.BytesValue.Builder builderForValue) {
        if (clientKeyBuilder_ == null) {
          clientKey_ = builderForValue.build();
          onChanged();
        } else {
          clientKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeClientKey(com.google.protobuf.BytesValue value) {
        if (clientKeyBuilder_ == null) {
          if (clientKey_ != null) {
            clientKey_ =
              com.google.protobuf.BytesValue.newBuilder(clientKey_).mergeFrom(value).buildPartial();
          } else {
            clientKey_ = value;
          }
          onChanged();
        } else {
          clientKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearClientKey() {
        if (clientKeyBuilder_ == null) {
          clientKey_ = null;
          onChanged();
        } else {
          clientKey_ = null;
          clientKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValue.Builder getClientKeyBuilder() {
        
        onChanged();
        return getClientKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValueOrBuilder getClientKeyOrBuilder() {
        if (clientKeyBuilder_ != null) {
          return clientKeyBuilder_.getMessageOrBuilder();
        } else {
          return clientKey_ == null ?
              com.google.protobuf.BytesValue.getDefaultInstance() : clientKey_;
        }
      }
      /**
       * <code>.google.protobuf.BytesValue client_key = 1 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> 
          getClientKeyFieldBuilder() {
        if (clientKeyBuilder_ == null) {
          clientKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                  getClientKey(),
                  getParentForChildren(),
                  isClean());
          clientKey_ = null;
        }
        return clientKeyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RequestKeyExchange)
    }

    // @@protoc_insertion_point(class_scope:dialog.RequestKeyExchange)
    private static final dialog.CryptoOuterClass.RequestKeyExchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.CryptoOuterClass.RequestKeyExchange();
    }

    public static dialog.CryptoOuterClass.RequestKeyExchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestKeyExchange>
        PARSER = new com.google.protobuf.AbstractParser<RequestKeyExchange>() {
      public RequestKeyExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestKeyExchange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestKeyExchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestKeyExchange> getParserForType() {
      return PARSER;
    }

    public dialog.CryptoOuterClass.RequestKeyExchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseKeyExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.ResponseKeyExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    boolean hasServerKey();
    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    com.google.protobuf.BytesValue getServerKey();
    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    com.google.protobuf.BytesValueOrBuilder getServerKeyOrBuilder();
  }
  /**
   * Protobuf type {@code dialog.ResponseKeyExchange}
   */
  public  static final class ResponseKeyExchange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.ResponseKeyExchange)
      ResponseKeyExchangeOrBuilder {
    // Use ResponseKeyExchange.newBuilder() to construct.
    private ResponseKeyExchange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseKeyExchange() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseKeyExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.BytesValue.Builder subBuilder = null;
              if (serverKey_ != null) {
                subBuilder = serverKey_.toBuilder();
              }
              serverKey_ = input.readMessage(com.google.protobuf.BytesValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverKey_);
                serverKey_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.CryptoOuterClass.internal_static_dialog_ResponseKeyExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.CryptoOuterClass.internal_static_dialog_ResponseKeyExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.CryptoOuterClass.ResponseKeyExchange.class, dialog.CryptoOuterClass.ResponseKeyExchange.Builder.class);
    }

    public static final int SERVER_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.BytesValue serverKey_;
    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    public boolean hasServerKey() {
      return serverKey_ != null;
    }
    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    public com.google.protobuf.BytesValue getServerKey() {
      return serverKey_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : serverKey_;
    }
    /**
     * <code>.google.protobuf.BytesValue server_key = 1;</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getServerKeyOrBuilder() {
      return getServerKey();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverKey_ != null) {
        output.writeMessage(1, getServerKey());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getServerKey());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.CryptoOuterClass.ResponseKeyExchange)) {
        return super.equals(obj);
      }
      dialog.CryptoOuterClass.ResponseKeyExchange other = (dialog.CryptoOuterClass.ResponseKeyExchange) obj;

      boolean result = true;
      result = result && (hasServerKey() == other.hasServerKey());
      if (hasServerKey()) {
        result = result && getServerKey()
            .equals(other.getServerKey());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerKey()) {
        hash = (37 * hash) + SERVER_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getServerKey().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.CryptoOuterClass.ResponseKeyExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.CryptoOuterClass.ResponseKeyExchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.ResponseKeyExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.ResponseKeyExchange)
        dialog.CryptoOuterClass.ResponseKeyExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.CryptoOuterClass.internal_static_dialog_ResponseKeyExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.CryptoOuterClass.internal_static_dialog_ResponseKeyExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.CryptoOuterClass.ResponseKeyExchange.class, dialog.CryptoOuterClass.ResponseKeyExchange.Builder.class);
      }

      // Construct using dialog.CryptoOuterClass.ResponseKeyExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (serverKeyBuilder_ == null) {
          serverKey_ = null;
        } else {
          serverKey_ = null;
          serverKeyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.CryptoOuterClass.internal_static_dialog_ResponseKeyExchange_descriptor;
      }

      public dialog.CryptoOuterClass.ResponseKeyExchange getDefaultInstanceForType() {
        return dialog.CryptoOuterClass.ResponseKeyExchange.getDefaultInstance();
      }

      public dialog.CryptoOuterClass.ResponseKeyExchange build() {
        dialog.CryptoOuterClass.ResponseKeyExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.CryptoOuterClass.ResponseKeyExchange buildPartial() {
        dialog.CryptoOuterClass.ResponseKeyExchange result = new dialog.CryptoOuterClass.ResponseKeyExchange(this);
        if (serverKeyBuilder_ == null) {
          result.serverKey_ = serverKey_;
        } else {
          result.serverKey_ = serverKeyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.CryptoOuterClass.ResponseKeyExchange) {
          return mergeFrom((dialog.CryptoOuterClass.ResponseKeyExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.CryptoOuterClass.ResponseKeyExchange other) {
        if (other == dialog.CryptoOuterClass.ResponseKeyExchange.getDefaultInstance()) return this;
        if (other.hasServerKey()) {
          mergeServerKey(other.getServerKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.CryptoOuterClass.ResponseKeyExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.CryptoOuterClass.ResponseKeyExchange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.BytesValue serverKey_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> serverKeyBuilder_;
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public boolean hasServerKey() {
        return serverKeyBuilder_ != null || serverKey_ != null;
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public com.google.protobuf.BytesValue getServerKey() {
        if (serverKeyBuilder_ == null) {
          return serverKey_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : serverKey_;
        } else {
          return serverKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public Builder setServerKey(com.google.protobuf.BytesValue value) {
        if (serverKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverKey_ = value;
          onChanged();
        } else {
          serverKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public Builder setServerKey(
          com.google.protobuf.BytesValue.Builder builderForValue) {
        if (serverKeyBuilder_ == null) {
          serverKey_ = builderForValue.build();
          onChanged();
        } else {
          serverKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public Builder mergeServerKey(com.google.protobuf.BytesValue value) {
        if (serverKeyBuilder_ == null) {
          if (serverKey_ != null) {
            serverKey_ =
              com.google.protobuf.BytesValue.newBuilder(serverKey_).mergeFrom(value).buildPartial();
          } else {
            serverKey_ = value;
          }
          onChanged();
        } else {
          serverKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public Builder clearServerKey() {
        if (serverKeyBuilder_ == null) {
          serverKey_ = null;
          onChanged();
        } else {
          serverKey_ = null;
          serverKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public com.google.protobuf.BytesValue.Builder getServerKeyBuilder() {
        
        onChanged();
        return getServerKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      public com.google.protobuf.BytesValueOrBuilder getServerKeyOrBuilder() {
        if (serverKeyBuilder_ != null) {
          return serverKeyBuilder_.getMessageOrBuilder();
        } else {
          return serverKey_ == null ?
              com.google.protobuf.BytesValue.getDefaultInstance() : serverKey_;
        }
      }
      /**
       * <code>.google.protobuf.BytesValue server_key = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> 
          getServerKeyFieldBuilder() {
        if (serverKeyBuilder_ == null) {
          serverKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                  getServerKey(),
                  getParentForChildren(),
                  isClean());
          serverKey_ = null;
        }
        return serverKeyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.ResponseKeyExchange)
    }

    // @@protoc_insertion_point(class_scope:dialog.ResponseKeyExchange)
    private static final dialog.CryptoOuterClass.ResponseKeyExchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.CryptoOuterClass.ResponseKeyExchange();
    }

    public static dialog.CryptoOuterClass.ResponseKeyExchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseKeyExchange>
        PARSER = new com.google.protobuf.AbstractParser<ResponseKeyExchange>() {
      public ResponseKeyExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseKeyExchange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseKeyExchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseKeyExchange> getParserForType() {
      return PARSER;
    }

    public dialog.CryptoOuterClass.ResponseKeyExchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RequestKeyExchange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RequestKeyExchange_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_ResponseKeyExchange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_ResponseKeyExchange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014crypto.proto\022\006dialog\032\036google/protobuf/" +
      "wrappers.proto\032\034google/api/annotations.p" +
      "roto\032\021definitions.proto\032\025scalapb/scalapb" +
      ".proto\"r\n\022RequestKeyExchange\022>\n\nclient_k" +
      "ey\030\001 \001(\0132\033.google.protobuf.BytesValueB\r\212" +
      "\3520\t\n\007compact:\034\342?\031\n\027im.dlg.grpc.GrpcReque" +
      "st\"e\n\023ResponseKeyExchange\022/\n\nserver_key\030" +
      "\001 \001(\0132\033.google.protobuf.BytesValue:\035\342?\032\n" +
      "\030im.dlg.grpc.GrpcResponse2x\n\006Crypto\022n\n\013K" +
      "eyExchange\022\032.dialog.RequestKeyExchange\032\033",
      ".dialog.ResponseKeyExchange\"&\202\323\344\223\002 \"\033/v1" +
      "/grpc/Crypto/KeyExchange:\001*B\031\342?\026\n\024im.dlg" +
      ".grpc.servicesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          dialog.Definitions.getDescriptor(),
          com.trueaccord.scalapb.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_dialog_RequestKeyExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialog_RequestKeyExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RequestKeyExchange_descriptor,
        new java.lang.String[] { "ClientKey", });
    internal_static_dialog_ResponseKeyExchange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialog_ResponseKeyExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_ResponseKeyExchange_descriptor,
        new java.lang.String[] { "ServerKey", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(dialog.Definitions.dlg);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.trueaccord.scalapb.Scalapb.message);
    registry.add(com.trueaccord.scalapb.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    dialog.Definitions.getDescriptor();
    com.trueaccord.scalapb.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
