// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_info.proto

package dialog;

public final class DeviceInfoOuterClass {
  private DeviceInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dialog.PlatformType}
   */
  public enum PlatformType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLATFORMTYPE_UNKNOWN = 0;</code>
     */
    PLATFORMTYPE_UNKNOWN(0),
    /**
     * <code>PLATFORMTYPE_ANDROID = 1;</code>
     */
    PLATFORMTYPE_ANDROID(1),
    /**
     * <code>PLATFORMTYPE_IOS = 2;</code>
     */
    PLATFORMTYPE_IOS(2),
    /**
     * <code>PLATFORMTYPE_WEB = 3;</code>
     */
    PLATFORMTYPE_WEB(3),
    /**
     * <code>PLATFORMTYPE_CLC = 4;</code>
     */
    PLATFORMTYPE_CLC(4),
    /**
     * <code>PLATFORMTYPE_TESTS = 42;</code>
     */
    PLATFORMTYPE_TESTS(42),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLATFORMTYPE_UNKNOWN = 0;</code>
     */
    public static final int PLATFORMTYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>PLATFORMTYPE_ANDROID = 1;</code>
     */
    public static final int PLATFORMTYPE_ANDROID_VALUE = 1;
    /**
     * <code>PLATFORMTYPE_IOS = 2;</code>
     */
    public static final int PLATFORMTYPE_IOS_VALUE = 2;
    /**
     * <code>PLATFORMTYPE_WEB = 3;</code>
     */
    public static final int PLATFORMTYPE_WEB_VALUE = 3;
    /**
     * <code>PLATFORMTYPE_CLC = 4;</code>
     */
    public static final int PLATFORMTYPE_CLC_VALUE = 4;
    /**
     * <code>PLATFORMTYPE_TESTS = 42;</code>
     */
    public static final int PLATFORMTYPE_TESTS_VALUE = 42;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlatformType valueOf(int value) {
      return forNumber(value);
    }

    public static PlatformType forNumber(int value) {
      switch (value) {
        case 0: return PLATFORMTYPE_UNKNOWN;
        case 1: return PLATFORMTYPE_ANDROID;
        case 2: return PLATFORMTYPE_IOS;
        case 3: return PLATFORMTYPE_WEB;
        case 4: return PLATFORMTYPE_CLC;
        case 42: return PLATFORMTYPE_TESTS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlatformType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlatformType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlatformType>() {
            public PlatformType findValueByNumber(int number) {
              return PlatformType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dialog.DeviceInfoOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlatformType[] VALUES = values();

    public static PlatformType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlatformType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dialog.PlatformType)
  }

  public interface RequestNotifyAboutDeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RequestNotifyAboutDeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    java.util.List<java.lang.String>
        getPreferredLanguagesList();
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    int getPreferredLanguagesCount();
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    java.lang.String getPreferredLanguages(int index);
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.ByteString
        getPreferredLanguagesBytes(int index);

    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasTimeZone();
    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValue getTimeZone();
    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder();
  }
  /**
   * <pre>
   * Notifying about device information
   * </pre>
   *
   * Protobuf type {@code dialog.RequestNotifyAboutDeviceInfo}
   */
  public  static final class RequestNotifyAboutDeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RequestNotifyAboutDeviceInfo)
      RequestNotifyAboutDeviceInfoOrBuilder {
    // Use RequestNotifyAboutDeviceInfo.newBuilder() to construct.
    private RequestNotifyAboutDeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestNotifyAboutDeviceInfo() {
      preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestNotifyAboutDeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                preferredLanguages_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              preferredLanguages_.add(s);
              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (timeZone_ != null) {
                subBuilder = timeZone_.toBuilder();
              }
              timeZone_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timeZone_);
                timeZone_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          preferredLanguages_ = preferredLanguages_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.DeviceInfoOuterClass.internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.DeviceInfoOuterClass.internal_static_dialog_RequestNotifyAboutDeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.class, dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PREFERRED_LANGUAGES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList preferredLanguages_;
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPreferredLanguagesList() {
      return preferredLanguages_;
    }
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    public int getPreferredLanguagesCount() {
      return preferredLanguages_.size();
    }
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    public java.lang.String getPreferredLanguages(int index) {
      return preferredLanguages_.get(index);
    }
    /**
     * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ByteString
        getPreferredLanguagesBytes(int index) {
      return preferredLanguages_.getByteString(index);
    }

    public static final int TIME_ZONE_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue timeZone_;
    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasTimeZone() {
      return timeZone_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValue getTimeZone() {
      return timeZone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
    }
    /**
     * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder() {
      return getTimeZone();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < preferredLanguages_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, preferredLanguages_.getRaw(i));
      }
      if (timeZone_ != null) {
        output.writeMessage(2, getTimeZone());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < preferredLanguages_.size(); i++) {
          dataSize += computeStringSizeNoTag(preferredLanguages_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPreferredLanguagesList().size();
      }
      if (timeZone_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimeZone());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo)) {
        return super.equals(obj);
      }
      dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo other = (dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo) obj;

      boolean result = true;
      result = result && getPreferredLanguagesList()
          .equals(other.getPreferredLanguagesList());
      result = result && (hasTimeZone() == other.hasTimeZone());
      if (hasTimeZone()) {
        result = result && getTimeZone()
            .equals(other.getTimeZone());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPreferredLanguagesCount() > 0) {
        hash = (37 * hash) + PREFERRED_LANGUAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPreferredLanguagesList().hashCode();
      }
      if (hasTimeZone()) {
        hash = (37 * hash) + TIME_ZONE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeZone().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Notifying about device information
     * </pre>
     *
     * Protobuf type {@code dialog.RequestNotifyAboutDeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RequestNotifyAboutDeviceInfo)
        dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_RequestNotifyAboutDeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.class, dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.Builder.class);
      }

      // Construct using dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (timeZoneBuilder_ == null) {
          timeZone_ = null;
        } else {
          timeZone_ = null;
          timeZoneBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor;
      }

      public dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo getDefaultInstanceForType() {
        return dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.getDefaultInstance();
      }

      public dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo build() {
        dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo buildPartial() {
        dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo result = new dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          preferredLanguages_ = preferredLanguages_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.preferredLanguages_ = preferredLanguages_;
        if (timeZoneBuilder_ == null) {
          result.timeZone_ = timeZone_;
        } else {
          result.timeZone_ = timeZoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo) {
          return mergeFrom((dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo other) {
        if (other == dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo.getDefaultInstance()) return this;
        if (!other.preferredLanguages_.isEmpty()) {
          if (preferredLanguages_.isEmpty()) {
            preferredLanguages_ = other.preferredLanguages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePreferredLanguagesIsMutable();
            preferredLanguages_.addAll(other.preferredLanguages_);
          }
          onChanged();
        }
        if (other.hasTimeZone()) {
          mergeTimeZone(other.getTimeZone());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePreferredLanguagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          preferredLanguages_ = new com.google.protobuf.LazyStringArrayList(preferredLanguages_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPreferredLanguagesList() {
        return preferredLanguages_.getUnmodifiableView();
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public int getPreferredLanguagesCount() {
        return preferredLanguages_.size();
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public java.lang.String getPreferredLanguages(int index) {
        return preferredLanguages_.get(index);
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ByteString
          getPreferredLanguagesBytes(int index) {
        return preferredLanguages_.getByteString(index);
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPreferredLanguages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePreferredLanguagesIsMutable();
        preferredLanguages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addPreferredLanguages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePreferredLanguagesIsMutable();
        preferredLanguages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addAllPreferredLanguages(
          java.lang.Iterable<java.lang.String> values) {
        ensurePreferredLanguagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, preferredLanguages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearPreferredLanguages() {
        preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addPreferredLanguagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePreferredLanguagesIsMutable();
        preferredLanguages_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue timeZone_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> timeZoneBuilder_;
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasTimeZone() {
        return timeZoneBuilder_ != null || timeZone_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue getTimeZone() {
        if (timeZoneBuilder_ == null) {
          return timeZone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
        } else {
          return timeZoneBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTimeZone(com.google.protobuf.StringValue value) {
        if (timeZoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeZone_ = value;
          onChanged();
        } else {
          timeZoneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTimeZone(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (timeZoneBuilder_ == null) {
          timeZone_ = builderForValue.build();
          onChanged();
        } else {
          timeZoneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeTimeZone(com.google.protobuf.StringValue value) {
        if (timeZoneBuilder_ == null) {
          if (timeZone_ != null) {
            timeZone_ =
              com.google.protobuf.StringValue.newBuilder(timeZone_).mergeFrom(value).buildPartial();
          } else {
            timeZone_ = value;
          }
          onChanged();
        } else {
          timeZoneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearTimeZone() {
        if (timeZoneBuilder_ == null) {
          timeZone_ = null;
          onChanged();
        } else {
          timeZone_ = null;
          timeZoneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue.Builder getTimeZoneBuilder() {
        
        onChanged();
        return getTimeZoneFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder() {
        if (timeZoneBuilder_ != null) {
          return timeZoneBuilder_.getMessageOrBuilder();
        } else {
          return timeZone_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 2 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getTimeZoneFieldBuilder() {
        if (timeZoneBuilder_ == null) {
          timeZoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getTimeZone(),
                  getParentForChildren(),
                  isClean());
          timeZone_ = null;
        }
        return timeZoneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RequestNotifyAboutDeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:dialog.RequestNotifyAboutDeviceInfo)
    private static final dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo();
    }

    public static dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestNotifyAboutDeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestNotifyAboutDeviceInfo>() {
      public RequestNotifyAboutDeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestNotifyAboutDeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestNotifyAboutDeviceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestNotifyAboutDeviceInfo> getParserForType() {
      return PARSER;
    }

    public dialog.DeviceInfoOuterClass.RequestNotifyAboutDeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.ClientInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
     */
    int getPlatformValue();
    /**
     * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
     */
    dialog.DeviceInfoOuterClass.PlatformType getPlatform();

    /**
     * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
     */
    java.lang.String getAppName();
    /**
     * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasAppVersion();
    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValue getAppVersion();
    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValueOrBuilder getAppVersionOrBuilder();

    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasSdkVersion();
    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValue getSdkVersion();
    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValueOrBuilder getSdkVersionOrBuilder();

    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    java.util.List<java.lang.String>
        getPreferredLanguagesList();
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    int getPreferredLanguagesCount();
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    java.lang.String getPreferredLanguages(int index);
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.ByteString
        getPreferredLanguagesBytes(int index);

    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasTimeZone();
    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValue getTimeZone();
    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder();
  }
  /**
   * <pre>
   * Generic client info, containing information about platform type, version, sdk etc
   * platform The platform enum. Can be either Android, Web or iOS
   * deviceName For android: vendor and model; For iOS: model; For Web: platform and user agent
   * appName Optional application name
   * appVersion Application version
   * sdkVersion Optional SDK version
   * preferredLanguages Optional ISO-639 language code and ISO-3166 country code: ru-RU
   * timeZone Optional TimeZone id
   * </pre>
   *
   * Protobuf type {@code dialog.ClientInfo}
   */
  public  static final class ClientInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.ClientInfo)
      ClientInfoOrBuilder {
    // Use ClientInfo.newBuilder() to construct.
    private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientInfo() {
      platform_ = 0;
      deviceName_ = "";
      appName_ = "";
      preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClientInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              platform_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (appVersion_ != null) {
                subBuilder = appVersion_.toBuilder();
              }
              appVersion_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(appVersion_);
                appVersion_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (sdkVersion_ != null) {
                subBuilder = sdkVersion_.toBuilder();
              }
              sdkVersion_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sdkVersion_);
                sdkVersion_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                preferredLanguages_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              preferredLanguages_.add(s);
              break;
            }
            case 58: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (timeZone_ != null) {
                subBuilder = timeZone_.toBuilder();
              }
              timeZone_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timeZone_);
                timeZone_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          preferredLanguages_ = preferredLanguages_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.DeviceInfoOuterClass.internal_static_dialog_ClientInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.DeviceInfoOuterClass.internal_static_dialog_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.DeviceInfoOuterClass.ClientInfo.class, dialog.DeviceInfoOuterClass.ClientInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PLATFORM_FIELD_NUMBER = 1;
    private int platform_;
    /**
     * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
     */
    public int getPlatformValue() {
      return platform_;
    }
    /**
     * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
     */
    public dialog.DeviceInfoOuterClass.PlatformType getPlatform() {
      dialog.DeviceInfoOuterClass.PlatformType result = dialog.DeviceInfoOuterClass.PlatformType.valueOf(platform_);
      return result == null ? dialog.DeviceInfoOuterClass.PlatformType.UNRECOGNIZED : result;
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceName_;
    /**
     * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object appName_;
    /**
     * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_VERSION_FIELD_NUMBER = 4;
    private com.google.protobuf.StringValue appVersion_;
    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasAppVersion() {
      return appVersion_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValue getAppVersion() {
      return appVersion_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : appVersion_;
    }
    /**
     * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValueOrBuilder getAppVersionOrBuilder() {
      return getAppVersion();
    }

    public static final int SDK_VERSION_FIELD_NUMBER = 5;
    private com.google.protobuf.StringValue sdkVersion_;
    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasSdkVersion() {
      return sdkVersion_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValue getSdkVersion() {
      return sdkVersion_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sdkVersion_;
    }
    /**
     * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValueOrBuilder getSdkVersionOrBuilder() {
      return getSdkVersion();
    }

    public static final int PREFERRED_LANGUAGES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList preferredLanguages_;
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPreferredLanguagesList() {
      return preferredLanguages_;
    }
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    public int getPreferredLanguagesCount() {
      return preferredLanguages_.size();
    }
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    public java.lang.String getPreferredLanguages(int index) {
      return preferredLanguages_.get(index);
    }
    /**
     * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.ByteString
        getPreferredLanguagesBytes(int index) {
      return preferredLanguages_.getByteString(index);
    }

    public static final int TIME_ZONE_FIELD_NUMBER = 7;
    private com.google.protobuf.StringValue timeZone_;
    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasTimeZone() {
      return timeZone_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValue getTimeZone() {
      return timeZone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
    }
    /**
     * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder() {
      return getTimeZone();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (platform_ != dialog.DeviceInfoOuterClass.PlatformType.PLATFORMTYPE_UNKNOWN.getNumber()) {
        output.writeEnum(1, platform_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceName_);
      }
      if (!getAppNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appName_);
      }
      if (appVersion_ != null) {
        output.writeMessage(4, getAppVersion());
      }
      if (sdkVersion_ != null) {
        output.writeMessage(5, getSdkVersion());
      }
      for (int i = 0; i < preferredLanguages_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, preferredLanguages_.getRaw(i));
      }
      if (timeZone_ != null) {
        output.writeMessage(7, getTimeZone());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (platform_ != dialog.DeviceInfoOuterClass.PlatformType.PLATFORMTYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, platform_);
      }
      if (!getDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceName_);
      }
      if (!getAppNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appName_);
      }
      if (appVersion_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAppVersion());
      }
      if (sdkVersion_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSdkVersion());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < preferredLanguages_.size(); i++) {
          dataSize += computeStringSizeNoTag(preferredLanguages_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPreferredLanguagesList().size();
      }
      if (timeZone_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getTimeZone());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.DeviceInfoOuterClass.ClientInfo)) {
        return super.equals(obj);
      }
      dialog.DeviceInfoOuterClass.ClientInfo other = (dialog.DeviceInfoOuterClass.ClientInfo) obj;

      boolean result = true;
      result = result && platform_ == other.platform_;
      result = result && getDeviceName()
          .equals(other.getDeviceName());
      result = result && getAppName()
          .equals(other.getAppName());
      result = result && (hasAppVersion() == other.hasAppVersion());
      if (hasAppVersion()) {
        result = result && getAppVersion()
            .equals(other.getAppVersion());
      }
      result = result && (hasSdkVersion() == other.hasSdkVersion());
      if (hasSdkVersion()) {
        result = result && getSdkVersion()
            .equals(other.getSdkVersion());
      }
      result = result && getPreferredLanguagesList()
          .equals(other.getPreferredLanguagesList());
      result = result && (hasTimeZone() == other.hasTimeZone());
      if (hasTimeZone()) {
        result = result && getTimeZone()
            .equals(other.getTimeZone());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + platform_;
      hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceName().hashCode();
      hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      if (hasAppVersion()) {
        hash = (37 * hash) + APP_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getAppVersion().hashCode();
      }
      if (hasSdkVersion()) {
        hash = (37 * hash) + SDK_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getSdkVersion().hashCode();
      }
      if (getPreferredLanguagesCount() > 0) {
        hash = (37 * hash) + PREFERRED_LANGUAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPreferredLanguagesList().hashCode();
      }
      if (hasTimeZone()) {
        hash = (37 * hash) + TIME_ZONE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeZone().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.DeviceInfoOuterClass.ClientInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.DeviceInfoOuterClass.ClientInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Generic client info, containing information about platform type, version, sdk etc
     * platform The platform enum. Can be either Android, Web or iOS
     * deviceName For android: vendor and model; For iOS: model; For Web: platform and user agent
     * appName Optional application name
     * appVersion Application version
     * sdkVersion Optional SDK version
     * preferredLanguages Optional ISO-639 language code and ISO-3166 country code: ru-RU
     * timeZone Optional TimeZone id
     * </pre>
     *
     * Protobuf type {@code dialog.ClientInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.ClientInfo)
        dialog.DeviceInfoOuterClass.ClientInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_ClientInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_ClientInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.DeviceInfoOuterClass.ClientInfo.class, dialog.DeviceInfoOuterClass.ClientInfo.Builder.class);
      }

      // Construct using dialog.DeviceInfoOuterClass.ClientInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        platform_ = 0;

        deviceName_ = "";

        appName_ = "";

        if (appVersionBuilder_ == null) {
          appVersion_ = null;
        } else {
          appVersion_ = null;
          appVersionBuilder_ = null;
        }
        if (sdkVersionBuilder_ == null) {
          sdkVersion_ = null;
        } else {
          sdkVersion_ = null;
          sdkVersionBuilder_ = null;
        }
        preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (timeZoneBuilder_ == null) {
          timeZone_ = null;
        } else {
          timeZone_ = null;
          timeZoneBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.DeviceInfoOuterClass.internal_static_dialog_ClientInfo_descriptor;
      }

      public dialog.DeviceInfoOuterClass.ClientInfo getDefaultInstanceForType() {
        return dialog.DeviceInfoOuterClass.ClientInfo.getDefaultInstance();
      }

      public dialog.DeviceInfoOuterClass.ClientInfo build() {
        dialog.DeviceInfoOuterClass.ClientInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.DeviceInfoOuterClass.ClientInfo buildPartial() {
        dialog.DeviceInfoOuterClass.ClientInfo result = new dialog.DeviceInfoOuterClass.ClientInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.platform_ = platform_;
        result.deviceName_ = deviceName_;
        result.appName_ = appName_;
        if (appVersionBuilder_ == null) {
          result.appVersion_ = appVersion_;
        } else {
          result.appVersion_ = appVersionBuilder_.build();
        }
        if (sdkVersionBuilder_ == null) {
          result.sdkVersion_ = sdkVersion_;
        } else {
          result.sdkVersion_ = sdkVersionBuilder_.build();
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          preferredLanguages_ = preferredLanguages_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.preferredLanguages_ = preferredLanguages_;
        if (timeZoneBuilder_ == null) {
          result.timeZone_ = timeZone_;
        } else {
          result.timeZone_ = timeZoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.DeviceInfoOuterClass.ClientInfo) {
          return mergeFrom((dialog.DeviceInfoOuterClass.ClientInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.DeviceInfoOuterClass.ClientInfo other) {
        if (other == dialog.DeviceInfoOuterClass.ClientInfo.getDefaultInstance()) return this;
        if (other.platform_ != 0) {
          setPlatformValue(other.getPlatformValue());
        }
        if (!other.getDeviceName().isEmpty()) {
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasAppVersion()) {
          mergeAppVersion(other.getAppVersion());
        }
        if (other.hasSdkVersion()) {
          mergeSdkVersion(other.getSdkVersion());
        }
        if (!other.preferredLanguages_.isEmpty()) {
          if (preferredLanguages_.isEmpty()) {
            preferredLanguages_ = other.preferredLanguages_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensurePreferredLanguagesIsMutable();
            preferredLanguages_.addAll(other.preferredLanguages_);
          }
          onChanged();
        }
        if (other.hasTimeZone()) {
          mergeTimeZone(other.getTimeZone());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.DeviceInfoOuterClass.ClientInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.DeviceInfoOuterClass.ClientInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int platform_ = 0;
      /**
       * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
       */
      public int getPlatformValue() {
        return platform_;
      }
      /**
       * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPlatformValue(int value) {
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
       */
      public dialog.DeviceInfoOuterClass.PlatformType getPlatform() {
        dialog.DeviceInfoOuterClass.PlatformType result = dialog.DeviceInfoOuterClass.PlatformType.valueOf(platform_);
        return result == null ? dialog.DeviceInfoOuterClass.PlatformType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPlatform(dialog.DeviceInfoOuterClass.PlatformType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        platform_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dialog.PlatformType platform = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearPlatform() {
        
        platform_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearDeviceName() {
        
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>string device_name = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>string app_name = 3 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue appVersion_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> appVersionBuilder_;
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasAppVersion() {
        return appVersionBuilder_ != null || appVersion_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue getAppVersion() {
        if (appVersionBuilder_ == null) {
          return appVersion_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : appVersion_;
        } else {
          return appVersionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setAppVersion(com.google.protobuf.StringValue value) {
        if (appVersionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          appVersion_ = value;
          onChanged();
        } else {
          appVersionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setAppVersion(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (appVersionBuilder_ == null) {
          appVersion_ = builderForValue.build();
          onChanged();
        } else {
          appVersionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeAppVersion(com.google.protobuf.StringValue value) {
        if (appVersionBuilder_ == null) {
          if (appVersion_ != null) {
            appVersion_ =
              com.google.protobuf.StringValue.newBuilder(appVersion_).mergeFrom(value).buildPartial();
          } else {
            appVersion_ = value;
          }
          onChanged();
        } else {
          appVersionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearAppVersion() {
        if (appVersionBuilder_ == null) {
          appVersion_ = null;
          onChanged();
        } else {
          appVersion_ = null;
          appVersionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue.Builder getAppVersionBuilder() {
        
        onChanged();
        return getAppVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValueOrBuilder getAppVersionOrBuilder() {
        if (appVersionBuilder_ != null) {
          return appVersionBuilder_.getMessageOrBuilder();
        } else {
          return appVersion_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : appVersion_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue app_version = 4 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getAppVersionFieldBuilder() {
        if (appVersionBuilder_ == null) {
          appVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getAppVersion(),
                  getParentForChildren(),
                  isClean());
          appVersion_ = null;
        }
        return appVersionBuilder_;
      }

      private com.google.protobuf.StringValue sdkVersion_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> sdkVersionBuilder_;
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasSdkVersion() {
        return sdkVersionBuilder_ != null || sdkVersion_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue getSdkVersion() {
        if (sdkVersionBuilder_ == null) {
          return sdkVersion_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sdkVersion_;
        } else {
          return sdkVersionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setSdkVersion(com.google.protobuf.StringValue value) {
        if (sdkVersionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sdkVersion_ = value;
          onChanged();
        } else {
          sdkVersionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setSdkVersion(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (sdkVersionBuilder_ == null) {
          sdkVersion_ = builderForValue.build();
          onChanged();
        } else {
          sdkVersionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeSdkVersion(com.google.protobuf.StringValue value) {
        if (sdkVersionBuilder_ == null) {
          if (sdkVersion_ != null) {
            sdkVersion_ =
              com.google.protobuf.StringValue.newBuilder(sdkVersion_).mergeFrom(value).buildPartial();
          } else {
            sdkVersion_ = value;
          }
          onChanged();
        } else {
          sdkVersionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearSdkVersion() {
        if (sdkVersionBuilder_ == null) {
          sdkVersion_ = null;
          onChanged();
        } else {
          sdkVersion_ = null;
          sdkVersionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue.Builder getSdkVersionBuilder() {
        
        onChanged();
        return getSdkVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValueOrBuilder getSdkVersionOrBuilder() {
        if (sdkVersionBuilder_ != null) {
          return sdkVersionBuilder_.getMessageOrBuilder();
        } else {
          return sdkVersion_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : sdkVersion_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue sdk_version = 5 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getSdkVersionFieldBuilder() {
        if (sdkVersionBuilder_ == null) {
          sdkVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getSdkVersion(),
                  getParentForChildren(),
                  isClean());
          sdkVersion_ = null;
        }
        return sdkVersionBuilder_;
      }

      private com.google.protobuf.LazyStringList preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePreferredLanguagesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          preferredLanguages_ = new com.google.protobuf.LazyStringArrayList(preferredLanguages_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPreferredLanguagesList() {
        return preferredLanguages_.getUnmodifiableView();
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public int getPreferredLanguagesCount() {
        return preferredLanguages_.size();
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public java.lang.String getPreferredLanguages(int index) {
        return preferredLanguages_.get(index);
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.ByteString
          getPreferredLanguagesBytes(int index) {
        return preferredLanguages_.getByteString(index);
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setPreferredLanguages(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePreferredLanguagesIsMutable();
        preferredLanguages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addPreferredLanguages(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePreferredLanguagesIsMutable();
        preferredLanguages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addAllPreferredLanguages(
          java.lang.Iterable<java.lang.String> values) {
        ensurePreferredLanguagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, preferredLanguages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearPreferredLanguages() {
        preferredLanguages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string preferred_languages = 6 [(.dialog.dlg) = { ... }</code>
       */
      public Builder addPreferredLanguagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePreferredLanguagesIsMutable();
        preferredLanguages_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue timeZone_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> timeZoneBuilder_;
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasTimeZone() {
        return timeZoneBuilder_ != null || timeZone_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue getTimeZone() {
        if (timeZoneBuilder_ == null) {
          return timeZone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
        } else {
          return timeZoneBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTimeZone(com.google.protobuf.StringValue value) {
        if (timeZoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeZone_ = value;
          onChanged();
        } else {
          timeZoneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setTimeZone(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (timeZoneBuilder_ == null) {
          timeZone_ = builderForValue.build();
          onChanged();
        } else {
          timeZoneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeTimeZone(com.google.protobuf.StringValue value) {
        if (timeZoneBuilder_ == null) {
          if (timeZone_ != null) {
            timeZone_ =
              com.google.protobuf.StringValue.newBuilder(timeZone_).mergeFrom(value).buildPartial();
          } else {
            timeZone_ = value;
          }
          onChanged();
        } else {
          timeZoneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearTimeZone() {
        if (timeZoneBuilder_ == null) {
          timeZone_ = null;
          onChanged();
        } else {
          timeZone_ = null;
          timeZoneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue.Builder getTimeZoneBuilder() {
        
        onChanged();
        return getTimeZoneFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder() {
        if (timeZoneBuilder_ != null) {
          return timeZoneBuilder_.getMessageOrBuilder();
        } else {
          return timeZone_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : timeZone_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue time_zone = 7 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getTimeZoneFieldBuilder() {
        if (timeZoneBuilder_ == null) {
          timeZoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getTimeZone(),
                  getParentForChildren(),
                  isClean());
          timeZone_ = null;
        }
        return timeZoneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.ClientInfo)
    }

    // @@protoc_insertion_point(class_scope:dialog.ClientInfo)
    private static final dialog.DeviceInfoOuterClass.ClientInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.DeviceInfoOuterClass.ClientInfo();
    }

    public static dialog.DeviceInfoOuterClass.ClientInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientInfo>
        PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
      public ClientInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientInfo> getParserForType() {
      return PARSER;
    }

    public dialog.DeviceInfoOuterClass.ClientInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RequestNotifyAboutDeviceInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_ClientInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_ClientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021device_info.proto\022\006dialog\032\036google/prot" +
      "obuf/wrappers.proto\032\034google/api/annotati" +
      "ons.proto\032\021definitions.proto\032\023miscellane" +
      "ous.proto\032\025scalapb/scalapb.proto\"\250\001\n\034Req" +
      "uestNotifyAboutDeviceInfo\022*\n\023preferred_l" +
      "anguages\030\001 \003(\tB\r\212\3520\t\n\007visible\022>\n\ttime_zo" +
      "ne\030\002 \001(\0132\034.google.protobuf.StringValueB\r" +
      "\212\3520\t\n\007visible:\034\342?\031\n\027im.dlg.grpc.GrpcRequ" +
      "est\"\370\002\n\nClientInfo\0225\n\010platform\030\001 \001(\0162\024.d" +
      "ialog.PlatformTypeB\r\212\3520\t\n\007visible\022\"\n\013dev",
      "ice_name\030\002 \001(\tB\r\212\3520\t\n\007visible\022\037\n\010app_nam" +
      "e\030\003 \001(\tB\r\212\3520\t\n\007visible\022@\n\013app_version\030\004 " +
      "\001(\0132\034.google.protobuf.StringValueB\r\212\3520\t\n" +
      "\007visible\022@\n\013sdk_version\030\005 \001(\0132\034.google.p" +
      "rotobuf.StringValueB\r\212\3520\t\n\007visible\022*\n\023pr" +
      "eferred_languages\030\006 \003(\tB\r\212\3520\t\n\007visible\022>" +
      "\n\ttime_zone\030\007 \001(\0132\034.google.protobuf.Stri" +
      "ngValueB\r\212\3520\t\n\007visible*\234\001\n\014PlatformType\022" +
      "\030\n\024PLATFORMTYPE_UNKNOWN\020\000\022\030\n\024PLATFORMTYP" +
      "E_ANDROID\020\001\022\024\n\020PLATFORMTYPE_IOS\020\002\022\024\n\020PLA",
      "TFORMTYPE_WEB\020\003\022\024\n\020PLATFORMTYPE_CLC\020\004\022\026\n" +
      "\022PLATFORMTYPE_TESTS\020*2\230\001\n\nDeviceInfo\022\211\001\n" +
      "\025NotifyAboutDeviceInfo\022$.dialog.RequestN" +
      "otifyAboutDeviceInfo\032\024.dialog.ResponseVo" +
      "id\"4\202\323\344\223\002.\")/v1/grpc/DeviceInfo/NotifyAb" +
      "outDeviceInfo:\001*B\031\342?\026\n\024im.dlg.grpc.servi" +
      "cesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          dialog.Definitions.getDescriptor(),
          dialog.Miscellaneous.getDescriptor(),
          com.trueaccord.scalapb.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialog_RequestNotifyAboutDeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RequestNotifyAboutDeviceInfo_descriptor,
        new java.lang.String[] { "PreferredLanguages", "TimeZone", });
    internal_static_dialog_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialog_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_ClientInfo_descriptor,
        new java.lang.String[] { "Platform", "DeviceName", "AppName", "AppVersion", "SdkVersion", "PreferredLanguages", "TimeZone", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(dialog.Definitions.dlg);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.trueaccord.scalapb.Scalapb.message);
    registry.add(com.trueaccord.scalapb.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    dialog.Definitions.getDescriptor();
    dialog.Miscellaneous.getDescriptor();
    com.trueaccord.scalapb.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
