// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raw_api.proto

package dialog;

public final class RawApi {
  private RawApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestRawRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RequestRawRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasService();
    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValue getService();
    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.StringValueOrBuilder getServiceOrBuilder();

    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.BytesValue getBody();
    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code dialog.RequestRawRequest}
   */
  public  static final class RequestRawRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RequestRawRequest)
      RequestRawRequestOrBuilder {
    // Use RequestRawRequest.newBuilder() to construct.
    private RequestRawRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestRawRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestRawRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (service_ != null) {
                subBuilder = service_.toBuilder();
              }
              service_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(service_);
                service_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.BytesValue.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.BytesValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RawApi.internal_static_dialog_RequestRawRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RawApi.internal_static_dialog_RequestRawRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RawApi.RequestRawRequest.class, dialog.RawApi.RequestRawRequest.Builder.class);
    }

    public static final int SERVICE_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue service_;
    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasService() {
      return service_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValue getService() {
      return service_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : service_;
    }
    /**
     * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.StringValueOrBuilder getServiceOrBuilder() {
      return getService();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.BytesValue body_;
    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.BytesValue getBody() {
      return body_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (service_ != null) {
        output.writeMessage(1, getService());
      }
      if (body_ != null) {
        output.writeMessage(2, getBody());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (service_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getService());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RawApi.RequestRawRequest)) {
        return super.equals(obj);
      }
      dialog.RawApi.RequestRawRequest other = (dialog.RawApi.RequestRawRequest) obj;

      boolean result = true;
      result = result && (hasService() == other.hasService());
      if (hasService()) {
        result = result && getService()
            .equals(other.getService());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasService()) {
        hash = (37 * hash) + SERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getService().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RawApi.RequestRawRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RawApi.RequestRawRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RawApi.RequestRawRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RawApi.RequestRawRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RawApi.RequestRawRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.RequestRawRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RequestRawRequest)
        dialog.RawApi.RequestRawRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RawApi.internal_static_dialog_RequestRawRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RawApi.internal_static_dialog_RequestRawRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RawApi.RequestRawRequest.class, dialog.RawApi.RequestRawRequest.Builder.class);
      }

      // Construct using dialog.RawApi.RequestRawRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (serviceBuilder_ == null) {
          service_ = null;
        } else {
          service_ = null;
          serviceBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RawApi.internal_static_dialog_RequestRawRequest_descriptor;
      }

      public dialog.RawApi.RequestRawRequest getDefaultInstanceForType() {
        return dialog.RawApi.RequestRawRequest.getDefaultInstance();
      }

      public dialog.RawApi.RequestRawRequest build() {
        dialog.RawApi.RequestRawRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RawApi.RequestRawRequest buildPartial() {
        dialog.RawApi.RequestRawRequest result = new dialog.RawApi.RequestRawRequest(this);
        if (serviceBuilder_ == null) {
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RawApi.RequestRawRequest) {
          return mergeFrom((dialog.RawApi.RequestRawRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RawApi.RequestRawRequest other) {
        if (other == dialog.RawApi.RequestRawRequest.getDefaultInstance()) return this;
        if (other.hasService()) {
          mergeService(other.getService());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RawApi.RequestRawRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RawApi.RequestRawRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue service_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> serviceBuilder_;
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasService() {
        return serviceBuilder_ != null || service_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue getService() {
        if (serviceBuilder_ == null) {
          return service_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : service_;
        } else {
          return serviceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setService(com.google.protobuf.StringValue value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          service_ = value;
          onChanged();
        } else {
          serviceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setService(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          service_ = builderForValue.build();
          onChanged();
        } else {
          serviceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeService(com.google.protobuf.StringValue value) {
        if (serviceBuilder_ == null) {
          if (service_ != null) {
            service_ =
              com.google.protobuf.StringValue.newBuilder(service_).mergeFrom(value).buildPartial();
          } else {
            service_ = value;
          }
          onChanged();
        } else {
          serviceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = null;
          onChanged();
        } else {
          service_ = null;
          serviceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValue.Builder getServiceBuilder() {
        
        onChanged();
        return getServiceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.StringValueOrBuilder getServiceOrBuilder() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilder();
        } else {
          return service_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : service_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue service = 1 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getService(),
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }

      private com.google.protobuf.BytesValue body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValue getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setBody(com.google.protobuf.BytesValue value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder setBody(
          com.google.protobuf.BytesValue.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder mergeBody(com.google.protobuf.BytesValue value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.BytesValue.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValue.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      public com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.BytesValue.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.BytesValue body = 2 [(.dialog.dlg) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RequestRawRequest)
    }

    // @@protoc_insertion_point(class_scope:dialog.RequestRawRequest)
    private static final dialog.RawApi.RequestRawRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RawApi.RequestRawRequest();
    }

    public static dialog.RawApi.RequestRawRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRawRequest>
        PARSER = new com.google.protobuf.AbstractParser<RequestRawRequest>() {
      public RequestRawRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestRawRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestRawRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestRawRequest> getParserForType() {
      return PARSER;
    }

    public dialog.RawApi.RequestRawRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseRawRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.ResponseRawRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    com.google.protobuf.BytesValue getBody();
    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code dialog.ResponseRawRequest}
   */
  public  static final class ResponseRawRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.ResponseRawRequest)
      ResponseRawRequestOrBuilder {
    // Use ResponseRawRequest.newBuilder() to construct.
    private ResponseRawRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseRawRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseRawRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.BytesValue.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.BytesValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RawApi.internal_static_dialog_ResponseRawRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RawApi.internal_static_dialog_ResponseRawRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RawApi.ResponseRawRequest.class, dialog.RawApi.ResponseRawRequest.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.BytesValue body_;
    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    public com.google.protobuf.BytesValue getBody() {
      return body_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.BytesValue body = 1;</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (body_ != null) {
        output.writeMessage(1, getBody());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBody());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RawApi.ResponseRawRequest)) {
        return super.equals(obj);
      }
      dialog.RawApi.ResponseRawRequest other = (dialog.RawApi.ResponseRawRequest) obj;

      boolean result = true;
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RawApi.ResponseRawRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RawApi.ResponseRawRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RawApi.ResponseRawRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RawApi.ResponseRawRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RawApi.ResponseRawRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.ResponseRawRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.ResponseRawRequest)
        dialog.RawApi.ResponseRawRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RawApi.internal_static_dialog_ResponseRawRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RawApi.internal_static_dialog_ResponseRawRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RawApi.ResponseRawRequest.class, dialog.RawApi.ResponseRawRequest.Builder.class);
      }

      // Construct using dialog.RawApi.ResponseRawRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RawApi.internal_static_dialog_ResponseRawRequest_descriptor;
      }

      public dialog.RawApi.ResponseRawRequest getDefaultInstanceForType() {
        return dialog.RawApi.ResponseRawRequest.getDefaultInstance();
      }

      public dialog.RawApi.ResponseRawRequest build() {
        dialog.RawApi.ResponseRawRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RawApi.ResponseRawRequest buildPartial() {
        dialog.RawApi.ResponseRawRequest result = new dialog.RawApi.ResponseRawRequest(this);
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RawApi.ResponseRawRequest) {
          return mergeFrom((dialog.RawApi.ResponseRawRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RawApi.ResponseRawRequest other) {
        if (other == dialog.RawApi.ResponseRawRequest.getDefaultInstance()) return this;
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RawApi.ResponseRawRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RawApi.ResponseRawRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.BytesValue body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public com.google.protobuf.BytesValue getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.BytesValue.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public Builder setBody(com.google.protobuf.BytesValue value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public Builder setBody(
          com.google.protobuf.BytesValue.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public Builder mergeBody(com.google.protobuf.BytesValue value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.BytesValue.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public com.google.protobuf.BytesValue.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      public com.google.protobuf.BytesValueOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.BytesValue.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.BytesValue body = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.ResponseRawRequest)
    }

    // @@protoc_insertion_point(class_scope:dialog.ResponseRawRequest)
    private static final dialog.RawApi.ResponseRawRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RawApi.ResponseRawRequest();
    }

    public static dialog.RawApi.ResponseRawRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseRawRequest>
        PARSER = new com.google.protobuf.AbstractParser<ResponseRawRequest>() {
      public ResponseRawRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseRawRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseRawRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseRawRequest> getParserForType() {
      return PARSER;
    }

    public dialog.RawApi.ResponseRawRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RequestRawRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RequestRawRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_ResponseRawRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_ResponseRawRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rraw_api.proto\022\006dialog\032\036google/protobuf" +
      "/wrappers.proto\032\034google/api/annotations." +
      "proto\032\021definitions.proto\032\025scalapb/scalap" +
      "b.proto\"\250\001\n\021RequestRawRequest\022<\n\007service" +
      "\030\001 \001(\0132\034.google.protobuf.StringValueB\r\212\352" +
      "0\t\n\007visible\0227\n\004body\030\002 \001(\0132\033.google.proto" +
      "buf.BytesValueB\014\212\3520\010\n\006hidden:\034\342?\031\n\027im.dl" +
      "g.grpc.GrpcRequest\"^\n\022ResponseRawRequest" +
      "\022)\n\004body\030\001 \001(\0132\033.google.protobuf.BytesVa" +
      "lue:\035\342?\032\n\030im.dlg.grpc.GrpcResponse2t\n\006Ra",
      "wAPI\022j\n\nRawRequest\022\031.dialog.RequestRawRe" +
      "quest\032\032.dialog.ResponseRawRequest\"%\202\323\344\223\002" +
      "\037\"\032/v1/grpc/RawAPI/RawRequest:\001*B\031\342?\026\n\024i" +
      "m.dlg.grpc.servicesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          dialog.Definitions.getDescriptor(),
          com.trueaccord.scalapb.Scalapb.getDescriptor(),
        }, assigner);
    internal_static_dialog_RequestRawRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialog_RequestRawRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RequestRawRequest_descriptor,
        new java.lang.String[] { "Service", "Body", });
    internal_static_dialog_ResponseRawRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialog_ResponseRawRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_ResponseRawRequest_descriptor,
        new java.lang.String[] { "Body", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(dialog.Definitions.dlg);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.trueaccord.scalapb.Scalapb.message);
    registry.add(com.trueaccord.scalapb.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    dialog.Definitions.getDescriptor();
    com.trueaccord.scalapb.Scalapb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
