// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dialog;

public final class RegistrationOuterClass {
  private RegistrationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestRegisterDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RequestRegisterDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes client_pk = 1;</code>
     */
    com.google.protobuf.ByteString getClientPk();

    /**
     * <code>int32 app_id = 2;</code>
     */
    int getAppId();

    /**
     * <code>string app_title = 3;</code>
     */
    java.lang.String getAppTitle();
    /**
     * <code>string app_title = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppTitleBytes();

    /**
     * <code>string device_title = 4;</code>
     */
    java.lang.String getDeviceTitle();
    /**
     * <code>string device_title = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTitleBytes();
  }
  /**
   * Protobuf type {@code dialog.RequestRegisterDevice}
   */
  public  static final class RequestRegisterDevice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RequestRegisterDevice)
      RequestRegisterDeviceOrBuilder {
    // Use RequestRegisterDevice.newBuilder() to construct.
    private RequestRegisterDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestRegisterDevice() {
      clientPk_ = com.google.protobuf.ByteString.EMPTY;
      appId_ = 0;
      appTitle_ = "";
      deviceTitle_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestRegisterDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              clientPk_ = input.readBytes();
              break;
            }
            case 16: {

              appId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appTitle_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceTitle_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RequestRegisterDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RequestRegisterDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RegistrationOuterClass.RequestRegisterDevice.class, dialog.RegistrationOuterClass.RequestRegisterDevice.Builder.class);
    }

    public static final int CLIENT_PK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientPk_;
    /**
     * <code>bytes client_pk = 1;</code>
     */
    public com.google.protobuf.ByteString getClientPk() {
      return clientPk_;
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>int32 app_id = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int APP_TITLE_FIELD_NUMBER = 3;
    private volatile java.lang.Object appTitle_;
    /**
     * <code>string app_title = 3;</code>
     */
    public java.lang.String getAppTitle() {
      java.lang.Object ref = appTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string app_title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppTitleBytes() {
      java.lang.Object ref = appTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_TITLE_FIELD_NUMBER = 4;
    private volatile java.lang.Object deviceTitle_;
    /**
     * <code>string device_title = 4;</code>
     */
    public java.lang.String getDeviceTitle() {
      java.lang.Object ref = deviceTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string device_title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTitleBytes() {
      java.lang.Object ref = deviceTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!clientPk_.isEmpty()) {
        output.writeBytes(1, clientPk_);
      }
      if (appId_ != 0) {
        output.writeInt32(2, appId_);
      }
      if (!getAppTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appTitle_);
      }
      if (!getDeviceTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceTitle_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!clientPk_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, clientPk_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (!getAppTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appTitle_);
      }
      if (!getDeviceTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceTitle_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RegistrationOuterClass.RequestRegisterDevice)) {
        return super.equals(obj);
      }
      dialog.RegistrationOuterClass.RequestRegisterDevice other = (dialog.RegistrationOuterClass.RequestRegisterDevice) obj;

      boolean result = true;
      result = result && getClientPk()
          .equals(other.getClientPk());
      result = result && (getAppId()
          == other.getAppId());
      result = result && getAppTitle()
          .equals(other.getAppTitle());
      result = result && getDeviceTitle()
          .equals(other.getDeviceTitle());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_PK_FIELD_NUMBER;
      hash = (53 * hash) + getClientPk().hashCode();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + APP_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getAppTitle().hashCode();
      hash = (37 * hash) + DEVICE_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestRegisterDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RegistrationOuterClass.RequestRegisterDevice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.RequestRegisterDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RequestRegisterDevice)
        dialog.RegistrationOuterClass.RequestRegisterDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestRegisterDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestRegisterDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RegistrationOuterClass.RequestRegisterDevice.class, dialog.RegistrationOuterClass.RequestRegisterDevice.Builder.class);
      }

      // Construct using dialog.RegistrationOuterClass.RequestRegisterDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientPk_ = com.google.protobuf.ByteString.EMPTY;

        appId_ = 0;

        appTitle_ = "";

        deviceTitle_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestRegisterDevice_descriptor;
      }

      public dialog.RegistrationOuterClass.RequestRegisterDevice getDefaultInstanceForType() {
        return dialog.RegistrationOuterClass.RequestRegisterDevice.getDefaultInstance();
      }

      public dialog.RegistrationOuterClass.RequestRegisterDevice build() {
        dialog.RegistrationOuterClass.RequestRegisterDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RegistrationOuterClass.RequestRegisterDevice buildPartial() {
        dialog.RegistrationOuterClass.RequestRegisterDevice result = new dialog.RegistrationOuterClass.RequestRegisterDevice(this);
        result.clientPk_ = clientPk_;
        result.appId_ = appId_;
        result.appTitle_ = appTitle_;
        result.deviceTitle_ = deviceTitle_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RegistrationOuterClass.RequestRegisterDevice) {
          return mergeFrom((dialog.RegistrationOuterClass.RequestRegisterDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RegistrationOuterClass.RequestRegisterDevice other) {
        if (other == dialog.RegistrationOuterClass.RequestRegisterDevice.getDefaultInstance()) return this;
        if (other.getClientPk() != com.google.protobuf.ByteString.EMPTY) {
          setClientPk(other.getClientPk());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (!other.getAppTitle().isEmpty()) {
          appTitle_ = other.appTitle_;
          onChanged();
        }
        if (!other.getDeviceTitle().isEmpty()) {
          deviceTitle_ = other.deviceTitle_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RegistrationOuterClass.RequestRegisterDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RegistrationOuterClass.RequestRegisterDevice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString clientPk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes client_pk = 1;</code>
       */
      public com.google.protobuf.ByteString getClientPk() {
        return clientPk_;
      }
      /**
       * <code>bytes client_pk = 1;</code>
       */
      public Builder setClientPk(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientPk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes client_pk = 1;</code>
       */
      public Builder clearClientPk() {
        
        clientPk_ = getDefaultInstance().getClientPk();
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>int32 app_id = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>int32 app_id = 2;</code>
       */
      public Builder setAppId(int value) {
        
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 app_id = 2;</code>
       */
      public Builder clearAppId() {
        
        appId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appTitle_ = "";
      /**
       * <code>string app_title = 3;</code>
       */
      public java.lang.String getAppTitle() {
        java.lang.Object ref = appTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppTitleBytes() {
        java.lang.Object ref = appTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_title = 3;</code>
       */
      public Builder setAppTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_title = 3;</code>
       */
      public Builder clearAppTitle() {
        
        appTitle_ = getDefaultInstance().getAppTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string app_title = 3;</code>
       */
      public Builder setAppTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appTitle_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceTitle_ = "";
      /**
       * <code>string device_title = 4;</code>
       */
      public java.lang.String getDeviceTitle() {
        java.lang.Object ref = deviceTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTitleBytes() {
        java.lang.Object ref = deviceTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_title = 4;</code>
       */
      public Builder setDeviceTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_title = 4;</code>
       */
      public Builder clearDeviceTitle() {
        
        deviceTitle_ = getDefaultInstance().getDeviceTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string device_title = 4;</code>
       */
      public Builder setDeviceTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceTitle_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RequestRegisterDevice)
    }

    // @@protoc_insertion_point(class_scope:dialog.RequestRegisterDevice)
    private static final dialog.RegistrationOuterClass.RequestRegisterDevice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RegistrationOuterClass.RequestRegisterDevice();
    }

    public static dialog.RegistrationOuterClass.RequestRegisterDevice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRegisterDevice>
        PARSER = new com.google.protobuf.AbstractParser<RequestRegisterDevice>() {
      public RequestRegisterDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestRegisterDevice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestRegisterDevice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestRegisterDevice> getParserForType() {
      return PARSER;
    }

    public dialog.RegistrationOuterClass.RequestRegisterDevice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseDeviceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.ResponseDeviceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes server_pk = 1;</code>
     */
    com.google.protobuf.ByteString getServerPk();

    /**
     * <code>int64 auth_id = 2;</code>
     */
    long getAuthId();

    /**
     * <code>string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code dialog.ResponseDeviceRequest}
   */
  public  static final class ResponseDeviceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.ResponseDeviceRequest)
      ResponseDeviceRequestOrBuilder {
    // Use ResponseDeviceRequest.newBuilder() to construct.
    private ResponseDeviceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseDeviceRequest() {
      serverPk_ = com.google.protobuf.ByteString.EMPTY;
      authId_ = 0L;
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseDeviceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              serverPk_ = input.readBytes();
              break;
            }
            case 16: {

              authId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RegistrationOuterClass.internal_static_dialog_ResponseDeviceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RegistrationOuterClass.internal_static_dialog_ResponseDeviceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RegistrationOuterClass.ResponseDeviceRequest.class, dialog.RegistrationOuterClass.ResponseDeviceRequest.Builder.class);
    }

    public static final int SERVER_PK_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString serverPk_;
    /**
     * <code>bytes server_pk = 1;</code>
     */
    public com.google.protobuf.ByteString getServerPk() {
      return serverPk_;
    }

    public static final int AUTH_ID_FIELD_NUMBER = 2;
    private long authId_;
    /**
     * <code>int64 auth_id = 2;</code>
     */
    public long getAuthId() {
      return authId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!serverPk_.isEmpty()) {
        output.writeBytes(1, serverPk_);
      }
      if (authId_ != 0L) {
        output.writeInt64(2, authId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!serverPk_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, serverPk_);
      }
      if (authId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, authId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RegistrationOuterClass.ResponseDeviceRequest)) {
        return super.equals(obj);
      }
      dialog.RegistrationOuterClass.ResponseDeviceRequest other = (dialog.RegistrationOuterClass.ResponseDeviceRequest) obj;

      boolean result = true;
      result = result && getServerPk()
          .equals(other.getServerPk());
      result = result && (getAuthId()
          == other.getAuthId());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_PK_FIELD_NUMBER;
      hash = (53 * hash) + getServerPk().hashCode();
      hash = (37 * hash) + AUTH_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuthId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.ResponseDeviceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RegistrationOuterClass.ResponseDeviceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.ResponseDeviceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.ResponseDeviceRequest)
        dialog.RegistrationOuterClass.ResponseDeviceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RegistrationOuterClass.internal_static_dialog_ResponseDeviceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RegistrationOuterClass.internal_static_dialog_ResponseDeviceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RegistrationOuterClass.ResponseDeviceRequest.class, dialog.RegistrationOuterClass.ResponseDeviceRequest.Builder.class);
      }

      // Construct using dialog.RegistrationOuterClass.ResponseDeviceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverPk_ = com.google.protobuf.ByteString.EMPTY;

        authId_ = 0L;

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RegistrationOuterClass.internal_static_dialog_ResponseDeviceRequest_descriptor;
      }

      public dialog.RegistrationOuterClass.ResponseDeviceRequest getDefaultInstanceForType() {
        return dialog.RegistrationOuterClass.ResponseDeviceRequest.getDefaultInstance();
      }

      public dialog.RegistrationOuterClass.ResponseDeviceRequest build() {
        dialog.RegistrationOuterClass.ResponseDeviceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RegistrationOuterClass.ResponseDeviceRequest buildPartial() {
        dialog.RegistrationOuterClass.ResponseDeviceRequest result = new dialog.RegistrationOuterClass.ResponseDeviceRequest(this);
        result.serverPk_ = serverPk_;
        result.authId_ = authId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RegistrationOuterClass.ResponseDeviceRequest) {
          return mergeFrom((dialog.RegistrationOuterClass.ResponseDeviceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RegistrationOuterClass.ResponseDeviceRequest other) {
        if (other == dialog.RegistrationOuterClass.ResponseDeviceRequest.getDefaultInstance()) return this;
        if (other.getServerPk() != com.google.protobuf.ByteString.EMPTY) {
          setServerPk(other.getServerPk());
        }
        if (other.getAuthId() != 0L) {
          setAuthId(other.getAuthId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RegistrationOuterClass.ResponseDeviceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RegistrationOuterClass.ResponseDeviceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString serverPk_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes server_pk = 1;</code>
       */
      public com.google.protobuf.ByteString getServerPk() {
        return serverPk_;
      }
      /**
       * <code>bytes server_pk = 1;</code>
       */
      public Builder setServerPk(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverPk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes server_pk = 1;</code>
       */
      public Builder clearServerPk() {
        
        serverPk_ = getDefaultInstance().getServerPk();
        onChanged();
        return this;
      }

      private long authId_ ;
      /**
       * <code>int64 auth_id = 2;</code>
       */
      public long getAuthId() {
        return authId_;
      }
      /**
       * <code>int64 auth_id = 2;</code>
       */
      public Builder setAuthId(long value) {
        
        authId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 auth_id = 2;</code>
       */
      public Builder clearAuthId() {
        
        authId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.ResponseDeviceRequest)
    }

    // @@protoc_insertion_point(class_scope:dialog.ResponseDeviceRequest)
    private static final dialog.RegistrationOuterClass.ResponseDeviceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RegistrationOuterClass.ResponseDeviceRequest();
    }

    public static dialog.RegistrationOuterClass.ResponseDeviceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseDeviceRequest>
        PARSER = new com.google.protobuf.AbstractParser<ResponseDeviceRequest>() {
      public ResponseDeviceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseDeviceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseDeviceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseDeviceRequest> getParserForType() {
      return PARSER;
    }

    public dialog.RegistrationOuterClass.ResponseDeviceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterDeprecatedDeviceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RegisterDeprecatedDeviceRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code dialog.RegisterDeprecatedDeviceRequest}
   */
  public  static final class RegisterDeprecatedDeviceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RegisterDeprecatedDeviceRequest)
      RegisterDeprecatedDeviceRequestOrBuilder {
    // Use RegisterDeprecatedDeviceRequest.newBuilder() to construct.
    private RegisterDeprecatedDeviceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterDeprecatedDeviceRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RegisterDeprecatedDeviceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RegisterDeprecatedDeviceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.class, dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest)) {
        return super.equals(obj);
      }
      dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest other = (dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.RegisterDeprecatedDeviceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RegisterDeprecatedDeviceRequest)
        dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RegisterDeprecatedDeviceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.class, dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.Builder.class);
      }

      // Construct using dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor;
      }

      public dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest getDefaultInstanceForType() {
        return dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.getDefaultInstance();
      }

      public dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest build() {
        dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest buildPartial() {
        dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest result = new dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest) {
          return mergeFrom((dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest other) {
        if (other == dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RegisterDeprecatedDeviceRequest)
    }

    // @@protoc_insertion_point(class_scope:dialog.RegisterDeprecatedDeviceRequest)
    private static final dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest();
    }

    public static dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterDeprecatedDeviceRequest>
        PARSER = new com.google.protobuf.AbstractParser<RegisterDeprecatedDeviceRequest>() {
      public RegisterDeprecatedDeviceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RegisterDeprecatedDeviceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterDeprecatedDeviceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterDeprecatedDeviceRequest> getParserForType() {
      return PARSER;
    }

    public dialog.RegistrationOuterClass.RegisterDeprecatedDeviceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestExchangeAuthIdForTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dialog.RequestExchangeAuthIdForToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 auth_id = 1;</code>
     */
    long getAuthId();

    /**
     * <code>bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code dialog.RequestExchangeAuthIdForToken}
   */
  public  static final class RequestExchangeAuthIdForToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dialog.RequestExchangeAuthIdForToken)
      RequestExchangeAuthIdForTokenOrBuilder {
    // Use RequestExchangeAuthIdForToken.newBuilder() to construct.
    private RequestExchangeAuthIdForToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestExchangeAuthIdForToken() {
      authId_ = 0L;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestExchangeAuthIdForToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              authId_ = input.readInt64();
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RequestExchangeAuthIdForToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialog.RegistrationOuterClass.internal_static_dialog_RequestExchangeAuthIdForToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.class, dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.Builder.class);
    }

    public static final int AUTH_ID_FIELD_NUMBER = 1;
    private long authId_;
    /**
     * <code>int64 auth_id = 1;</code>
     */
    public long getAuthId() {
      return authId_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (authId_ != 0L) {
        output.writeInt64(1, authId_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (authId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, authId_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken)) {
        return super.equals(obj);
      }
      dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken other = (dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken) obj;

      boolean result = true;
      result = result && (getAuthId()
          == other.getAuthId());
      result = result && getSignature()
          .equals(other.getSignature());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTH_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuthId());
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dialog.RequestExchangeAuthIdForToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dialog.RequestExchangeAuthIdForToken)
        dialog.RegistrationOuterClass.RequestExchangeAuthIdForTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestExchangeAuthIdForToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestExchangeAuthIdForToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.class, dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.Builder.class);
      }

      // Construct using dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        authId_ = 0L;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dialog.RegistrationOuterClass.internal_static_dialog_RequestExchangeAuthIdForToken_descriptor;
      }

      public dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken getDefaultInstanceForType() {
        return dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.getDefaultInstance();
      }

      public dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken build() {
        dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken buildPartial() {
        dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken result = new dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken(this);
        result.authId_ = authId_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken) {
          return mergeFrom((dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken other) {
        if (other == dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken.getDefaultInstance()) return this;
        if (other.getAuthId() != 0L) {
          setAuthId(other.getAuthId());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long authId_ ;
      /**
       * <code>int64 auth_id = 1;</code>
       */
      public long getAuthId() {
        return authId_;
      }
      /**
       * <code>int64 auth_id = 1;</code>
       */
      public Builder setAuthId(long value) {
        
        authId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 auth_id = 1;</code>
       */
      public Builder clearAuthId() {
        
        authId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dialog.RequestExchangeAuthIdForToken)
    }

    // @@protoc_insertion_point(class_scope:dialog.RequestExchangeAuthIdForToken)
    private static final dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken();
    }

    public static dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestExchangeAuthIdForToken>
        PARSER = new com.google.protobuf.AbstractParser<RequestExchangeAuthIdForToken>() {
      public RequestExchangeAuthIdForToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestExchangeAuthIdForToken(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestExchangeAuthIdForToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestExchangeAuthIdForToken> getParserForType() {
      return PARSER;
    }

    public dialog.RegistrationOuterClass.RequestExchangeAuthIdForToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RequestRegisterDevice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RequestRegisterDevice_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_ResponseDeviceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_ResponseDeviceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RegisterDeprecatedDeviceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialog_RequestExchangeAuthIdForToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialog_RequestExchangeAuthIdForToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022registration.proto\022\006dialog\032\025scalapb/sc" +
      "alapb.proto\032\034google/api/annotations.prot" +
      "o\"\201\001\n\025RequestRegisterDevice\022\021\n\tclient_pk" +
      "\030\001 \001(\014\022\016\n\006app_id\030\002 \001(\005\022\021\n\tapp_title\030\003 \001(" +
      "\t\022\024\n\014device_title\030\004 \001(\t:\034\342?\031\n\027im.dlg.grp" +
      "c.GrpcRequest\"i\n\025ResponseDeviceRequest\022\021" +
      "\n\tserver_pk\030\001 \001(\014\022\017\n\007auth_id\030\002 \001(\003\022\r\n\005to" +
      "ken\030\003 \001(\t:\035\342?\032\n\030im.dlg.grpc.GrpcResponse" +
      "\"!\n\037RegisterDeprecatedDeviceRequest\"C\n\035R" +
      "equestExchangeAuthIdForToken\022\017\n\007auth_id\030",
      "\001 \001(\003\022\021\n\tsignature\030\002 \001(\0142\311\003\n\014Registratio" +
      "n\022\227\001\n\026ExchangeAuthIdForToken\022%.dialog.Re" +
      "questExchangeAuthIdForToken\032\035.dialog.Res" +
      "ponseDeviceRequest\"7\202\323\344\223\0021\",/v1/grpc/Reg" +
      "istration/ExchangeAuthIdForToken:\001*\022\177\n\016R" +
      "egisterDevice\022\035.dialog.RequestRegisterDe" +
      "vice\032\035.dialog.ResponseDeviceRequest\"/\202\323\344" +
      "\223\002)\"$/v1/grpc/Registration/RegisterDevic" +
      "e:\001*\022\235\001\n\030RegisterDeprecatedDevice\022\'.dial" +
      "og.RegisterDeprecatedDeviceRequest\032\035.dia",
      "log.ResponseDeviceRequest\"9\202\323\344\223\0023\"./v1/g" +
      "rpc/Registration/RegisterDeprecatedDevic" +
      "e:\001*B\031\342?\026\n\024im.dlg.grpc.servicesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.trueaccord.scalapb.Scalapb.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_dialog_RequestRegisterDevice_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialog_RequestRegisterDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RequestRegisterDevice_descriptor,
        new java.lang.String[] { "ClientPk", "AppId", "AppTitle", "DeviceTitle", });
    internal_static_dialog_ResponseDeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialog_ResponseDeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_ResponseDeviceRequest_descriptor,
        new java.lang.String[] { "ServerPk", "AuthId", "Token", });
    internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dialog_RegisterDeprecatedDeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RegisterDeprecatedDeviceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_dialog_RequestExchangeAuthIdForToken_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dialog_RequestExchangeAuthIdForToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialog_RequestExchangeAuthIdForToken_descriptor,
        new java.lang.String[] { "AuthId", "Signature", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.trueaccord.scalapb.Scalapb.message);
    registry.add(com.trueaccord.scalapb.Scalapb.options);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.trueaccord.scalapb.Scalapb.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
